export default {
    "language": "Langue",
    "locale": "fr-FR",
    "cancel": "Annuler",
    // home
    "connectCamera" : "Connecter la caméra",
    "disconnectCamera" : "Déconnecter la caméra",
    "observer" : "Observateur",
    "ipAddress" : "Adresse IP",
    "backendApiVersion" : "Version du firmware",
    "storage" : "Stockage",
    "freeStorage" : "libre", 
    "totalStorage" : "total",
    "longitude" : "Longitude",
    "latitude" : "Latitude",
    "altitude" : "Altitude",
    "sunrise" : "Lever",
    "sunset" : "Coucher",
    "transit" : "Transit",
    "sun" : "Soleil",
    "lowStorageWarning" : "Espace de stockage faible, veuillez libérer de l'espace avant de lancer un nouveau scan",
    // settings
    "configuration": "Configuration",
    "debugMode": "Mode debug",
    "debugDescription": "Permet d'afficher les logs de traitements des scans et d'activer des fonctionnalités.",
    "hotspotMode": "Mode hotspot",
    "hotspotDescription": "Mode par défaut, connectez vous au réseau wifi SUNSCAN",
    "updateFirmware": "Mise à jour du firmware",
    "updateFirmwareDescription": "Une mise à jour du firmware est disponible",
    "security": "Sécurité démarage",
    "securityDescription": "Si activé, SUNSCAN s'allumera seulement après un appui bref suivi d'un appui long (5s) sur le bouton de l'appareil",
    "offlineMode": "Mode hors connexion",
    "offlineDescription": "Force l'affichage des contrôles de la caméra même si sunscan n'est pas connecté",
    "sunscanIP": "IP Sunscan",
    "sunscanIPDescription": "Mode hotspot désactivé, précisez ici l'ip de votre SUNSCAN",
    "update": "Mettre à jour",
    "clearImageCache": "Vider le cache d'images",
    "clearCacheDescription": "Vide le cache d'images pour libérer de l'espace",
    "updateFirmwareconfirm": "Etes vous certain de vouloir mettre à jour le firmware ? Il est préférable de brancher l'alimentation de votre SUNSCAN pendant la mise à jour.",
    "firmwareIsOutdated": "Votre firmware est obsolète, veuillez mettre à jour le firmware dans la partie réglage de l'application",
    "firmwarePostUpdateMessage": "Le firmware a été mis à jour, veuillez redémarrer l'application et votre SUNSCAN pour appliquer les changements",
    "upToDate": "Vous avez la dernière version",
    "clearCacheConfirm": "Voulez-vous vraiment vider le cache d'images ?",
    "shutdown": "Eteindre SUNSCAN",
    "shutdownConfirm": "Etes vous certain de vouloir éteindre votre SUNSCAN ?",
    "shutdownOk": "Votre SUNSCAN va s'éteindre dans quelques secondes...",
    "reboot": "Redémarrer SUNSCAN",
    "rebootConfirm": "Etes vous certain de vouloir redémarrer votre SUNSCAN ?",
    "rebootOk": "Votre SUNSCAN va redémarrer dans quelques secondes...",
    "currentVersion": "Version actuelle",
    "newVersion": "Nouvelle version disponible",
    "displayWatermark": "Afficher un filigrane",
    "displayWatermarkDescription": "Affiche le logo SUNSCAN et le nom de l'observateur en bas à gauche de l'image",
    "globalConfiguration": "Configuration globale",
    "stackingConfiguration": "Options de stacking",
    "patchSize": "Patch size",
    "stepSize": "Step size",
    "intensityThreshold": "Intensity threshold",
    "reset": "Default values",
    "resetView": "Réinitialiser la vue",
    // picture screen
    "downloaded": "Téléchargement terminé",
    "downloading": "Téléchargement en cours",
    "download": "Télécharger",
    "delete": "Supprimer",
    "deleteConfirm": "êtes vous certain de vouloir supprimer ce scan ?",
    "deleteStackedConfirm": "êtes vous certain de vouloir supprimer cette images empilée ?",
    "deleteGenericConfirm": "êtes vous certain de vouloir supprimer ces éléments ?",
    "warning": "Attention",
    // scan screen
    "snapShot": "Snapshot",
    "color": "Couleur",
    "norm": "Norm",
    "adjust": "Réglages",
    "grid": "Grille",
    "focus": "Focus",
    "focusMsg": "Score de mise au point",
    "focusMsg1": "Positionner le soleil au centre de manière a ce qu'il soit le plus large possible puis",
    "focusMsg2": "maximiser le score ci-dessus en faisant la mise au point de la lunette à l'avant de SUNSCAN.",
    "auto": "Auto",
    "advancedProcessing":"Traitement du scan",
    "advancedProcessingOptions":"Mode avancé",
    "noiseReduction":"Réduction du bruit",
    "dopplerShift":"Doppler (+/-)",
    "offset":"Offset",
    "continuumShift":"Décalage continuum",
    "surfaceSharpenLevel":"Niveau de réhaussement image de la surface",
    "continuumSharpenLevel":"Niveau de réhaussement image du continuum ",
    "protusSharpenLevel":"Niveau de réhaussement image de l'éclipse artificielle",
    "Off":"Désactivé",
    "Low":"Bas",
    "Medium":"Moyen",
    "High":"Haut",
    "startProcessing": "Lancer le traitement",
    "pleaseWait": "Le traitement peut prendre plusieurs minutes...",
    "verticalProfile":"Profil vertical / Mise au point caméra",
    "horizontalProfile":"Profil horizontal / Mise au point lunette",
    "verticalProfileTitle" : "Spectre",
    "horizontalProfileTitle":"Continuum",
    "helium":"Traitement Helium",
    "selectLineMessage": "Veuillez sélectionner la raie correspondante à votre scan.",
    "dopplerColor": "Couleur Doppler",
    "orangeblue": "Orange-Bleu",
    "redblue": "Rouge-Bleu",
    // scan info
    "typeImage": "Type d'image",
    "acquisitionTime": "Heure d'acquisition",
    "filePath": "Chemin fichier source",
    "scanPath": "Chemin fichier scan",
    "acquisitionSettings": "Paramètre d'acquisition",
    "camera": "Caméra",
    "exposure": "Exposition",
    "gain": "Gain",
    "processingLog": "Log de traitement",
    "scanSelected": "scans selectionnés",
    "delete": "Supprimer",
    "stack": "Additionner",
    "animate": "Animer",
    // list screen
    "scans": "Scans",
    "stacked": "Stacked",
    "animations": "Animations",
    "snapshots": "Snapshots",
    "processing": "Traitement en cours",
    // animation options modal
    "animationOptions": "Options d'animation",
    "frameDuration": "Durée de chaque image (ms)",
    "displayDatetime": "Afficher la date et l'heure",
    "resizeGif": "Redimensionner le GIF (50%)",
    "bidirectional": "Animation bidirectionnel",
    "addAverageFrame": "Ajouter des images moyennes entre chaque frame",
    "startProcessing": "Démarrer le traitement",
    "pleaseWait": "Le traitement peut prendre plusieurs minutes...",
    "selectAtLeastOneItem": "Veuillez sélectionner au moins deux éléments",
    "disconnectCameraBeforeStacking" : "Veuillez déconnecter la caméra pour pouvoir aditionner des images",
}