export default {
    "language": "Langue",
    "locale": "fr-FR",
    "cancel": "Annuler",
    // home
    "connectCamera" : "Connecter la caméra",
    "disconnectCamera" : "Déconnecter la caméra",
    "observer" : "Observateur",
    "ipAddress" : "Adresse IP",
    "backendApiVersion" : "Version du firmware",
    "storage" : "Stockage",
    "usedStorage" : "utilisé", 
    "totalStorage" : "total",
    "longitude" : "Longitude",
    "latitude" : "Latitude",
    "altitude" : "Altitude",
    "sunrise" : "Lever",
    "sunset" : "Coucher",
    "transit" : "Transit",
    "sun" : "Soleil",
    // settings
    "configuration": "Configuration",
    "debugMode": "Mode debug",
    "debugDescription": "Permet d'afficher les logs de traitements des scans et d'activer des fonctionnalités.",
    "hotspotMode": "Mode hotspot",
    "hotspotDescription": "Mode par défaut, connectez vous au réseau wifi SUNSCAN",
    "updateFirmware": "Mise à jour du firmware",
    "updateFirmwareDescription": "Une mise à jour du firmware est disponible",
    "security": "Sécurité démarage",
    "securityDescription": "Si activé, SUNSCAN s'allumera seulement après un appui bref suivi d'un appui long (5s) sur le bouton de l'appareil",
    "offlineMode": "Mode hors connexion",
    "offlineDescription": "Force l'affichage des contrôles de la caméra même si sunscan n'est pas connecté",
    "sunscanIP": "IP Sunscan",
    "sunscanIPDescription": "Mode hotspot désactivé, précisez ici l'ip de votre SUNSCAN",
    "update": "Mise à jour",
    "clearImageCache": "Vider le cache d'images",
    "clearCacheDescription": "Vide le cache d'images pour libérer de l'espace",
    "updateFirmwareconfirm": "Etes vous certain de vouloir mettre à jour le firmware ?",
    "upToDate": "Vous avez la dernière version",
    "clearCacheConfirm": "Voulez-vous vraiment vider le cache d'images ?",
    // picture screen
    "downloaded": "Téléchargement terminé",
    "downloading": "Téléchargement en cours",
    "download": "Télécharger",
    "delete": "Supprimer",
    "deleteConfirm": "etes vous certain de vouloir supprimer ce scan ?",
    "warning": "Attention",
    // scan screen
    "snapShot": "Snapshot",
    "color": "Couleur",
    "norm": "Norm",
    "adjust": "Exp",
    "grid": "Grille",
    "advancedProcessing":"Traitement du scan",
    "advancedProcessingOptions":"Mode avancé",
    "noiseReduction":"Réduction du bruit",
    "dopplerShift":"Décalage doppler",
    "continuumShift":"Décalage continuum",
    "surfaceSharpenLevel":"Niveau de réhaussement image de la surface",
    "continuumSharpenLevel":"Niveau de réhaussement image du continuum ",
    "protusSharpenLevel":"Niveau de réhaussement image de l'éclipse artificielle",
    "Off":"Désactivé",
    "Low":"Bas",
    "Medium":"Moyen",
    "High":"Haut",
    "startProcessing": "Lancer le traitement",
    "pleaseWait": "Le traitement peut prendre plusieurs minutes...",
    // scan info
    "typeImage": "Type d'image",
    "acquisitionTime": "Heure d'acquisition",
    "filePath": "Chemin fichier source",
    "scanPath": "Chemin fichier scan",
    "acquisitionSettings": "Paramètre d'acquisition",
    "camera": "Caméra",
    "exposure": "Exposition",
    "gain": "Gain",
    "processingLog": "Log de traitement",

}