export default {
    "language": "Langue",
    "locale": "fr-FR",
    "cancel": "Annuler",
    // home
    "connectCamera" : "Connecter la caméra",
    "disconnectCamera" : "Déconnecter la caméra",
    "observer" : "Observateur",
    "ipAddress" : "Adresse IP",
    "backendApiVersion" : "Version du firmware",
    "storage" : "Stockage",
    "freeStorage" : "libre", 
    "totalStorage" : "total",
    "longitude" : "Longitude",
    "latitude" : "Latitude",
    "altitude" : "Altitude",
    "sunrise" : "Lever",
    "sunset" : "Coucher",
    "transit" : "Transit",
    "sun" : "Soleil",
    "cameraNotConnected" : "Caméra non connectée",
    "simulated" : "simulé",
    "cropRequiredTitle" : "Recadrez d'abord la fenêtre",
    "cropRequiredMsg" : "Appuyez sur le bouton de recadrage pour passer en mode scan, puis lancez l'acquisition.",
    "lowStorageWarning" : "Espace de stockage faible, veuillez libérer de l'espace avant de lancer un nouveau scan",
    "storageCleanupHint" : "Pensez à faire du ménage",
    // settings
    "configuration": "Configuration",
    "debugMode": "Mode debug",
    "debugDescription": "Permet d'afficher les logs de traitements des scans et d'activer des fonctionnalités.",
    "hotspotMode": "Mode hotspot",
    "hotspotDescription": "Mode par défaut, connectez vous au réseau wifi SUNSCAN",
    "updateFirmware": "Mise à jour du firmware",
    "updateFirmwareDescription": "Une mise à jour du firmware est disponible",
    "security": "Sécurité démarage",
    "securityDescription": "Si activé, SUNSCAN s'allumera seulement après un appui bref suivi d'un appui long (5s) sur le bouton de l'appareil",
    "offlineMode": "Mode hors connexion",
    "offlineDescription": "Force l'affichage des contrôles de la caméra même si sunscan n'est pas connecté",
    "sunscanIP": "IP Sunscan",
    "sunscanIPDescription": "Mode hotspot désactivé, précisez ici l'ip de votre SUNSCAN",
    "searchSunscan": "Rechercher le SUNSCAN",
    "searching": "Recherche en cours",
    "sunscanFound": "SUNSCAN trouvé à l'adresse {{url}}",
    "sunscanNotFound": "Aucun SUNSCAN trouvé sur ce réseau. Vérifiez que votre SUNSCAN est allumé et connecté au même réseau wifi que votre téléphone, ou saisissez son adresse IP manuellement.",
    "success": "Succès",
    "update": "Mettre à jour",
    "clearImageCache": "Vider le cache d'images",
    "clearCacheDescription": "Vide le cache d'images pour libérer de l'espace",
    "updateFirmwareconfirm": "Etes vous certain de vouloir mettre à jour le firmware ? Il est préférable de brancher l'alimentation de votre SUNSCAN pendant la mise à jour.",
    "firmwareIsOutdated": "Votre firmware est obsolète, veuillez mettre à jour le firmware dans la partie réglage de l'application",
    "firmwarePostUpdateMessage": "Le firmware a été mis à jour, veuillez redémarrer l'application et votre SUNSCAN pour appliquer les changements",
    "firmwareUpdating": "Mise à jour...",
    "firmwareUpdateUnconfirmed": "Impossible de confirmer la mise à jour du firmware. Vérifiez que votre SUNSCAN est allumé et connecté, redémarrez-le, puis réessayez.",
    "upToDate": "Vous avez la dernière version",
    "clearCacheConfirm": "Voulez-vous vraiment vider le cache d'images ?",
    "shutdown": "Eteindre SUNSCAN",
    "shutdownConfirm": "Etes vous certain de vouloir éteindre votre SUNSCAN ?",
    "shutdownOk": "Votre SUNSCAN va s'éteindre dans quelques secondes...",
    "reboot": "Redémarrer SUNSCAN",
    "rebootConfirm": "Etes vous certain de vouloir redémarrer votre SUNSCAN ?",
    "rebootOk": "Votre SUNSCAN va redémarrer dans quelques secondes...",
    "currentVersion": "Version actuelle",
    "newVersion": "Nouvelle version disponible",
    "displayWatermark": "Afficher un filigrane",
    "displayWatermarkDescription": "Affiche le logo SUNSCAN et le nom de l'observateur en bas à gauche de l'image",
    "globalConfiguration": "Configuration globale",
    "screenOrientation": "Orientation de l'écran",
    "screenOrientationDescription": "Auto : s'adapte à la rotation du téléphone, ou verrouiller une orientation",
    "cameraLeft": "Caméra à gauche",
    "cameraRight": "Caméra à droite",
    "stackingConfiguration": "Options de stacking",
    "patchSize": "Patch size",
    "stepSize": "Step size",
    "intensityThreshold": "Intensity threshold",
    "reset": "Default values",
    "resetView": "Réinitialiser la vue",
    // picture screen
    "downloaded": "Téléchargement terminé",
    "downloading": "Téléchargement en cours",
    "downloadError": "Échec du téléchargement",
    "download": "Télécharger",
    "delete": "Supprimer",
    "deleteConfirm": "êtes vous certain de vouloir supprimer ce scan ?",
    "deleteStackedConfirm": "êtes vous certain de vouloir supprimer cette images empilée ?",
    "deleteGenericConfirm": "êtes vous certain de vouloir supprimer ces éléments ?",
    "warning": "Attention",
    // scan screen
    "snapShot": "Snapshot",
    "color": "Couleur",
    "norm": "Norm",
    "adjust": "Réglages",
    "grid": "Grille",
    "focus": "Focus",
    "focusMsg": "Score de mise au point",
    "focusReset": "Réinitialiser",
    "focusWaiting": "Mesure de la netteté…",
    "focusBest": "meilleur : {{value}}",
    "focusNewBest": "Nouveau meilleur !",
    "focusStep1": "Centrez le Soleil sur la fente pour qu'il soit le plus large possible.",
    "focusStep2": "Tournez la mise au point de la lunette avant : la barre doit monter.",
    "focusStep3": "Dépassez légèrement le pic (flèche rouge), puis revenez jusqu'à ~100 %.",
    "auto": "Auto",
    "advancedProcessing":"Traitement avancé du scan",
    "advancedProcessingOptions":"Mode avancé",
    "noiseReduction":"Réduction du bruit",
    "dopplerShift":"Doppler (+/-)",
    "offset":"Offset",
    "continuumShift":"Décalage continuum",
    "surfaceSharpenLevel":"Niveau de réhaussement image de la surface",
    "continuumSharpenLevel":"Niveau de réhaussement image du continuum ",
    "protusSharpenLevel":"Niveau de réhaussement image de l'éclipse artificielle",
    "Off":"Désactivé",
    "Low":"Bas",
    "Medium":"Moyen",
    "High":"Haut",
    "startProcessing": "Lancer le traitement",
    "verticalProfile":"Profil vertical / Mise au point caméra",
    "horizontalProfile":"Profil horizontal / Mise au point lunette",
    "verticalProfileTitle" : "Spectre",
    "horizontalProfileTitle":"Continuum",
    "helium":"Traitement Helium",
    "scanCompleteTitle": "Scan terminé",
    "otherLine": "Autre",
    "selectLineMessage": "Veuillez sélectionner la raie correspondante à votre scan.",
    "dopplerColor": "Couleur Doppler",
    "orangeblue": "Orange-Bleu",
    "redblue": "Rouge-Bleu",
    "doppler": "Calculer l'image Doppler",
    // scan info
    "typeImage": "Type d'image",
    "acquisitionTime": "Heure d'acquisition",
    "filePath": "Chemin fichier source",
    "scanPath": "Chemin fichier scan",
    "acquisitionSettings": "Paramètre d'acquisition",
    "camera": "Caméra",
    "exposure": "Exposition",
    "gain": "Gain",
    "processingLog": "Log de traitement",
    "scanSelected": "scans selectionnés",
    "delete": "Supprimer",
    "stack": "Additionner",
    "animate": "Animer",
    // list screen
    "scans": "Scans",
    "stacked": "Stacked",
    "animations": "Animations",
    "snapshots": "Snapshots",
    "processing": "Traitement en cours",
    // animation options modal
    "animationOptions": "Options d'animation",
    "frameDuration": "Durée de chaque image (ms)",
    "displayDatetime": "Afficher la date et l'heure",
    "resizeGif": "Redimensionner le GIF (50%)",
    "bidirectional": "Animation bidirectionnel",
    "addAverageFrame": "Ajouter des images moyennes entre chaque frame",
    "startProcessing": "Démarrer le traitement",
    "selectAtLeastOneItem": "Veuillez sélectionner au moins deux éléments",
    "disconnectCameraBeforeStacking" : "Veuillez déconnecter la caméra pour pouvoir aditionner des images",
    // settings sections
    "connectionSection": "Connexion",
    "deviceSection": "Appareil",
    "advancedSection": "Avancé",
    "emptyGallery": "Aucun élément à afficher",
    // processing steps (narration shown while a scan is processed)
    "stepReadingSer": "Lecture du fichier SER",
    "stepMeanImage": "Calcul de l'image moyenne",
    "stepDetectingLine": "Détection de la raie spectrale",
    "stepPolynomialFit": "Ajustement du polynôme de courbure",
    "stepReconstructing": "Reconstruction du disque solaire",
    "stepTiltCorrection": "Correction du tilt et de la géométrie",
    "stepScaling": "Mise à l'échelle du disque",
    "stepCircleDetection": "Détection du limbe et centrage",
    "stepSurface": "Génération de l'image de surface",
    "stepContinuum": "Génération du continuum",
    "stepProtus": "Extraction des protubérances",
    "stepDoppler": "Calcul de l'image Doppler",
    "stepClahe": "Amélioration du contraste (CLAHE)",
    "stepWatermark": "Application du filigrane",
    "stepSaving": "Enregistrement des images",
    // live processing progress, published by the backend on scan_progress_<key>
    "processStepStarting": "Traitement en file d'attente",
    "processStepReadingScan": "Lecture du fichier SER",
    "processStepBuildingDisk": "Reconstruction du disque",
    "processStepCorrectingGeometry": "Correction de la géométrie",
    "processStepImageSurface": "Génération des images de surface",
    "processStepImageContinuum": "Génération du continuum",
    "processStepImageProminences": "Extraction des protubérances",
    "processStepImageDoppler": "Calcul des images Doppler",
    "processStepImageHelium": "Génération des images hélium",
    "processStepDone": "Terminé",
    "processStepGeneric": "Traitement en cours",
    "processErrorFileNotFound": "Fichier SER introuvable sur le SUNSCAN",
    "processErrorReconstructionFailed": "Disque solaire non reconstruit : scan trop court, ou pas de Soleil",
    "processErrorImageGenerationFailed": "Disque reconstruit, mais les images n'ont pas pu être générées",
    "processErrorGeneric": "Le traitement a échoué",
    // pop-in d'addition d'images (stacking)
    "stackingTitle": "Addition des images",
    "stackingFrames": "{{number}} images sélectionnées",
    "stackingElapsed": "Temps écoulé : {{time}}",
    "stackingHint": "Le SUNSCAN ne signale pas son avancement. Ne quittez pas l'écran.",
    "stackingFailed": "L'addition a échoué",
    "stackingFailedHint": "Vérifiez la connexion au SUNSCAN, puis réessayez.",
    // assistant d'alignement du scan
    "assistant": "Assist.",
    "shearAngle": "incl.",
    "quality_excellent": "Fenêtre idéale",
    "quality_good": "Bonne fenêtre",
    "quality_fair": "Exploitable",
    "quality_poor": "Fortement incliné",
    "quality_impossible": "Disque trop grand",
    "assistantSunDown": "Soleil sous l'horizon",
    "assistantNoLocation": "En attente d'une position GPS pour calculer le scan",
    "assistantLocationDenied": "Localisation refusée : l'assistant a besoin de votre position",
    "assistantLocationUnavailable": "Position GPS introuvable",
    "assistantOpenSettings": "toucher pour ouvrir les réglages",
    "assistantRetry": "toucher pour réessayer",
    "assistantNoSignal": "Centrez le Soleil sur la fente pour démarrer le guidage",
    "assistantShiftBy": "Amenez le disque sur le repère ({{amount}})",
    "assistantReady": "En place — faites sortir le Soleil en amont, puis lancez",
    "assistantArmed": "Soleil hors de la fente, lancez le scan",
    "assistantWontFit": "Le disque ne tient pas, rapprochez-vous du midi solaire",
    "assistantWindow": "idéal {{start}}–{{end}}",
    "assistantScanRemaining": "≈ {{seconds}} s restantes",
    "assistantScanComplete": "Le disque a fini de passer, vous pouvez arrêter",
    "scanPreview": "aperçu du disque",
    "autoStopIn": "Arrêt auto dans {{seconds}} s",
    "autoStopCancel": "toucher pour annuler",
    // identification des raies spectrales
    "ident": "Ident.",
    "identStarting": "Démarrage…",
    "identSearching": "Localisation du spectre…",
    "identUnknown": "Spectre non reconnu",
    "identDark": "Pas assez de lumière : placez le Soleil sur la fente",
    "identSaturated": "Saturé : réduisez l'exposition",
    "identFlat": "Aucune raie visible : vérifiez la mise au point",
    "identShort": "Spectre trop étroit pour être identifié",
    "identSilent": "Aucun profil reçu du SUNSCAN",
    "identUnsupported": "Mise à jour du SUNSCAN requise",
    "identLines": "{{n}} raies",
    "identSolar": "Soleil",
    "identTelluric": "Atmosphère terrestre",
    // home wifi
    "wifiNetwork": "WiFi du SUNSCAN",
    "wifiModeHotspot": "Hotspot {{ssid}}",
    "wifiModeClient": "Connecté à {{ssid}} ({{ip}})",
    "wifiModeConnecting": "Connexion en cours…",
    "wifiModeDisconnected": "Déconnecté",
    "wifiConnectHome": "Connecter à mon WiFi",
    "wifiBackToHotspot": "Revenir au hotspot",
    "wifiBackToHotspotConfirm": "Le SUNSCAN va repasser sur son hotspot {{hotspot}} et la connexion va être coupée. Les réseaux enregistrés sont conservés : au prochain démarrage, il rejoindra votre WiFi s'il est à portée.",
    "wifiRejoinHotspot": "Connectez votre téléphone au réseau WiFi {{hotspot}}.",
    "wifiSavedNetworks": "Réseaux enregistrés",
    "wifiSavedNetworksHint": "Rejoints automatiquement au démarrage s'ils sont à portée.",
    "wifiForget": "Oublier",
    "wifiForgetConfirm": "Oublier {{ssid}} ? Le SUNSCAN ne rejoindra plus ce réseau.",
    "wifiForgetCurrentConfirm": "Oublier {{ssid}} ? Le SUNSCAN est actuellement sur ce réseau : il va repasser sur son hotspot {{hotspot}} et la connexion va être coupée.",
    "wifiChooseNetwork": "Choisissez votre réseau WiFi",
    "wifiScanning": "Le SUNSCAN recherche les réseaux…",
    "wifiScanCached": "La recherche a échoué, voici les résultats précédents.",
    "wifiRetry": "Réessayer",
    "wifiNoNetwork": "Aucun réseau trouvé.",
    "wifiOtherNetwork": "Autre réseau…",
    "wifiUnsupported": "non supporté",
    "wifiSaved": "enregistré",
    "wifiInUse": "actuel",
    "wifiSsid": "Nom du réseau (SSID)",
    "wifiPassword": "Mot de passe",
    "wifiPasswordOptional": "Mot de passe (vide si aucun)",
    "wifiConnect": "Se connecter",
    "wifiClose": "Fermer",
    "wifiJoining": "Le SUNSCAN rejoint {{ssid}}…",
    "wifiJoiningHint": "La connexion avec le SUNSCAN va être coupée, c'est normal.",
    "wifiPutPhoneOn": "Connectez maintenant votre téléphone à {{ssid}}.",
    "wifiOpenWifiSettings": "Ouvrir les réglages WiFi",
    "wifiConnected": "SUNSCAN connecté à {{ssid}}",
    "wifiConnectedHint": "L'application le joint maintenant à l'adresse {{url}}. Loin de ce réseau, le SUNSCAN relance son hotspot : réactivez alors le mode hotspot dans les réglages.",
    "wifiFailedHint": "Le SUNSCAN est revenu sur son hotspot {{hotspot}}.",
    "wifiLost": "SUNSCAN introuvable",
    "wifiLostPhone": "Vérifiez que votre téléphone est sur {{ssid}},",
    "wifiLostHotspot": "ou reconnectez-le au hotspot {{hotspot}}.",
    "wifiSearchAgain": "Relancer la recherche",
    "wifiEnterIp": "Saisir l'IP",
    "wifiUnreachable": "Impossible de joindre le SUNSCAN.",
    "wifiError_invalid_ssid": "Nom de réseau invalide",
    "wifiError_invalid_password": "Le mot de passe doit faire entre 8 et 63 caractères",
    "wifiError_unsupported_security": "Ce type de réseau (WEP, entreprise) n'est pas supporté",
    "wifiError_busy": "Une connexion est déjà en cours, réessayez dans une minute",
    "wifiError_not_supported": "Ce SUNSCAN ne peut pas rejoindre un réseau WiFi",
    "wifiError_wrong_password": "Mot de passe incorrect",
    "wifiError_network_not_found": "Réseau introuvable (hors de portée, ou nom mal saisi)",
    "wifiError_timeout": "Le réseau n'a pas répondu à temps",
    "wifiError_no_address": "Connecté, mais la box n'a pas donné d'adresse",
    "wifiError_connection_failed": "La connexion a échoué",
}
