export default {
    "language": "Idioma",
    "locale": "es-ES",
    "cancel": "Cancelar",
    // home
    "connectCamera": "Conectar cámara",
    "disconnectCamera": "Desconectar cámara",
    "observer": "Observador",
    "ipAddress": "Dirección IP",
    "storage": "Almacenamiento",
    "freeStorage": "libre",
    "totalStorage": "Total",
    "backendApiVersion": "Versión API Backend",
    "longitude": "Longitud",
    "latitude": "Latitud",
    "altitude": "Altitud",
    "sunrise": "Salida",
    "sunset": "Puesta",
    "transit": "Tránsito",
    "sun": "Sol",
    "lowStorageWarning": "Poco espacio de almacenamiento, por favor libere espacio antes de iniciar un nuevo escaneo",
    // settings
    "configuration": "Configuración",
    "debugMode": "Modo de depuración",
    "debugDescription": "Activa la visualización de registros de procesamiento y funciones de depuración.",
    "hotspotMode": "Modo punto de acceso",
    "hotspotDescription": "Por defecto, conéctese a la red wifi SUNSCAN.",
    "updateFirmware": "Actualizar firmware",
    "updateFirmwareDescription": "Hay una actualización del firmware disponible.",
    "security": "Seguridad",
    "securityDescription": "Si está habilitado, SUNSCAN solo se encenderá después de un toque corto en el dispositivo y un toque largo (5s) en el botón.",
    "offlineMode": "Modo sin conexión",
    "offlineDescription": "Fuerza la visualización de los controles de la cámara incluso si SUNSCAN no está conectado.",
    "sunscanIP": "IP de SUNSCAN",
    "sunscanIPDescription": "Modo punto de acceso desactivado, por favor ingrese aquí la IP de su SUNSCAN.",
    "update": "Actualizar",
    "clearImageCache": "Limpiar caché de imágenes",
    "clearCacheDescription": "Limpia la caché de imágenes para liberar espacio.",
    "updateFirmwareconfirm": "¿Está seguro de que desea actualizar el firmware? Se recomienda encender su SUNSCAN durante la actualización.",
    "firmwareIsOutdated": "Su firmware está desactualizado, por favor actualice el firmware en la configuración de la aplicación",
    "upToDate": "Tiene la última versión",
    "firmwarePostUpdateMessage": "El firmware ha sido actualizado, por favor reinicie la aplicación y su SUNSCAN para aplicar los cambios",
    "clearCacheConfirm": "¿Está seguro de que desea limpiar la caché de imágenes?",
    "shutdown": "Apagar SUNSCAN",
    "shutdownConfirm": "¿Está seguro de que desea apagar su SUNSCAN?",
    "shutdownOk": "Su SUNSCAN se apagará en unos segundos...",
    "reboot": "Reiniciar SUNSCAN",
    "rebootConfirm": "¿Está seguro de que desea reiniciar su SUNSCAN?",
    "rebootOk": "Su SUNSCAN se reiniciará en unos segundos...",
    "currentVersion": "Versión actual",
    "newVersion": "Nueva versión disponible",
    "displayWatermark": "Mostrar marca de agua",
    "displayWatermarkDescription": "Muestra el logo de SUNSCAN y el nombre del observador en la esquina inferior izquierda de la imagen",
    "globalConfiguration": "Configuración global",
    "screenOrientation": "Orientación de pantalla",
    "screenOrientationDescription": "Auto: se adapta a la rotación del teléfono, o bloquea a una orientación específica",
    "cameraLeft": "Cámara Izquierda",
    "cameraRight": "Cámara Derecha",
    "stackingConfiguration": "Opciones de apilado",
    "patchSize": "Tamaño de parche",
    "stepSize": "Tamaño de paso",
    "intensityThreshold": "Umbral de intensidad",
    "reset": "Valores predeterminados",
    "resetView": "Restablecer vista",
    // status
    "sunscan": "SUNSCAN",
    "storage": "Almacenamiento",
    "freeStorage": "Libre",
    "camera": "Cámara",
    "connect": "Conectar",
    "disconnect": "Desconectar",
    "refresh": "Actualizar",
    "ipAddress": "Dirección IP",
    "backendApiVersion": "Versión API Backend",
    "debug": "Depuración",
    "security": "Seguridad",
    "hotspotMode": "Modo punto de acceso",
    "offlineMode": "Modo sin conexión",
    "updateFirmware": "Actualizar firmware",
    // picture screen
    "downloaded": "Descargado",
    "downloading": "Descargando",
    "download": "Descargar",
    "delete": "Eliminar",
    "deleteConfirm": "¿Está seguro de que desea eliminar este escaneo?",
    "deleteStackedConfirm": "¿Está seguro de que desea eliminar estas imágenes apiladas?",
    "deleteGenericConfirm": "¿Está seguro de que desea eliminar estos elementos?",
    "warning": "Advertencia",
    // scan screen
    "snapShot": "Instantánea",
    "color": "Color",
    "norm": "Normal",
    "adjust": "Ajustar",
    "grid": "Cuadrícula",
    "focus": "Enfoque",
    "focusMsg": "Puntuación de enfoque",
    "focusMsg1": "Centre el sol tanto como sea posible para hacerlo lo más grande posible, luego",
    "focusMsg2": "maximice la puntuación anterior enfocando la parte frontal de la lente SUNSCAN.",
    "auto": "Auto",
    "advancedProcessing": "Procesamiento avanzado de escaneo",
    "advancedProcessingOptions": "Modo avanzado",
    "noiseReduction": "Reducción de ruido",
    "offset": "Desplazamiento",
    "dopplerShift": "Doppler (+/-)",
    "continuumShift": "Desplazamiento del continuo",
    "surfaceSharpenLevel": "Nivel de nitidez de imagen de superficie",
    "continuumSharpenLevel": "Nivel de nitidez de imagen del continuo",
    "protusSharpenLevel": "Nivel de nitidez de imagen de eclipse artificial",
    "Off": "Apagado",
    "Low": "Bajo",
    "Medium": "Medio",
    "High": "Alto",
    "startProcessing": "Iniciar procesamiento",
    "pleaseWait": "El procesamiento puede tardar varios minutos...",
    "verticalProfile": "perfil vertical / enfoque de cámara",
    "horizontalProfile": "perfil horizontal / enfoque de telescopio",
    "verticalProfileTitle": "Espectro",
    "horizontalProfileTitle": "Continuo",
    "helium": "Procesamiento de helio",
    "selectLineMessage": "Por favor, seleccione la línea correspondiente a su escaneo.",
    "dopplerColor": "Color Doppler",
    "orangeblue": "Naranja-Azul",
    "redblue": "Rojo-Azul",
    "doppler": "Calcular imagen Doppler",
    // scan info
    "typeImage": "Tipo de imagen",
    "acquisitionTime": "Tiempo de adquisición",
    "filePath": "Ruta del archivo",
    "scanPath": "Ruta de escaneo",
    "acquisitionSettings": "Configuración de adquisición",
    "camera": "Cámara",
    "exposure": "Exposición",
    "gain": "Ganancia",
    "processingLog": "Registro de procesamiento",
    "scanSelected": "escaneos seleccionados",
    "delete": "Eliminar",
    "stack": "Apilar",
    "animate": "Animar",
    // list screen
    "scans": "Escaneos",
    "stacked": "Apilados",
    "animations": "Animaciones",
    "snapshots": "Instantáneas",
    "processing": "Procesamiento en curso",
    // animation options modal
    "animationOptions": "Opciones de animación",
    "frameDuration": "Duración del fotograma (ms)",
    "displayDatetime": "Mostrar fecha y hora",
    "resizeGif": "Redimensionar GIF (50%)",
    "bidirectional": "Bidireccional",
    "addAverageFrame": "Añadir fotograma promedio",
    "startProcessing": "Iniciar procesamiento",
    "pleaseWait": "El procesamiento puede tardar varios minutos...",
    "selectAtLeastOneItem": "Por favor seleccione al menos dos elementos",
    "disconnectCameraBeforeStacking": "Por favor desconecte la cámara antes de apilar imágenes",
}