export default {
    "language": "Idioma",
    "locale": "es-ES",
    "cancel": "Cancelar",
    // splash
    "splashCredits" : "Por el equipo STAROS",
    // home
    "connectCamera": "Conectar cámara",
    "disconnectCamera": "Desconectar cámara",
    "observer": "Observador",
    "ipAddress": "Dirección IP",
    "storage": "Almacenamiento",
    "freeStorage": "libre",
    "totalStorage": "Total",
    "backendApiVersion": "Versión API Backend",
    "longitude": "Longitud",
    "latitude": "Latitud",
    "altitude": "Altitud",
    "sunrise": "Salida",
    "sunset": "Puesta",
    "transit": "Tránsito",
    "sun": "Sol",
    "cameraNotConnected": "Cámara no conectada",
    "simulated": "simulado",
    "cropRequiredTitle" : "Recorte primero la ventana",
    "cropRequiredMsg" : "Pulse el botón de recorte para pasar al modo escaneo y luego inicie la adquisición.",
    "lowStorageWarning": "Poco espacio de almacenamiento, por favor libere espacio antes de iniciar un nuevo escaneo",
    "storageCleanupHint": "Hora de limpiar sus escaneos",
    // settings
    "configuration": "Configuración",
    "debugMode": "Modo de depuración",
    "debugDescription": "Activa la visualización de registros de procesamiento y funciones de depuración.",
    "hotspotMode": "Modo punto de acceso",
    "hotspotDescription": "Por defecto, conéctese a la red wifi SUNSCAN.",
    "updateFirmware": "Actualizar firmware",
    "updateFirmwareDescription": "Hay una actualización del firmware disponible.",
    "security": "Seguridad",
    "securityDescription": "Si está habilitado, SUNSCAN solo se encenderá después de un toque corto en el dispositivo y un toque largo (5s) en el botón.",
    "offlineMode": "Modo sin conexión",
    "offlineDescription": "Fuerza la visualización de los controles de la cámara incluso si SUNSCAN no está conectado.",
    "sunscanIP": "IP de SUNSCAN",
    "sunscanIPDescription": "Modo punto de acceso desactivado, por favor ingrese aquí la IP de su SUNSCAN.",
    "searchSunscan": "Buscar el SUNSCAN",
    "searching": "Buscando",
    "sunscanFound": "SUNSCAN encontrado en {{url}}",
    "sunscanNotFound": "No se encontró ningún SUNSCAN en esta red. Compruebe que su SUNSCAN esté encendido y conectado a la misma red wifi que su teléfono, o introduzca su dirección IP manualmente.",
    "success": "Éxito",
    "update": "Actualizar",
    "clearImageCache": "Limpiar caché de imágenes",
    "clearCacheDescription": "Limpia la caché de imágenes para liberar espacio.",
    "updateFirmwareconfirm": "¿Está seguro de que desea actualizar el firmware? Se recomienda encender su SUNSCAN durante la actualización.",
    "firmwareIsOutdated": "Su firmware está desactualizado, por favor actualice el firmware en la configuración de la aplicación",
    "upToDate": "Tiene la última versión",
    "firmwarePostUpdateMessage": "Reinicie la aplicación y su SUNSCAN.",
    "firmwareUpdating": "Actualizando...",
    "firmwareUpdateUnconfirmed": "Compruebe que su SUNSCAN está encendido y conectado, y vuelva a intentarlo.",
    "firmwareAvailableSubtitle": "Nueva versión disponible",
    "firmwareOutdatedRisk": "Opcional, pero sin ella la aplicación será muy probablemente inestable.",
    "firmwareUpdateTips": "Conecte su SUNSCAN y mantenga la app abierta (~1 min).",
    "firmwareUpdateNow": "Actualizar ahora",
    "firmwareLater": "Más tarde",
    "firmwareUpdatingHint": "No cierre la app ni apague su SUNSCAN.",
    "firmwareUpdatedTitle": "Firmware actualizado",
    "firmwareFailedTitle": "Actualización no confirmada",
    "firmwareRetry": "Reintentar",
    "firmwareCurrent": "Actual",
    "firmwareNew": "Nueva",
    "clearCacheConfirm": "¿Está seguro de que desea limpiar la caché de imágenes?",
    "shutdown": "Apagar SUNSCAN",
    "shutdownConfirm": "¿Está seguro de que desea apagar su SUNSCAN?",
    "shutdownOk": "Su SUNSCAN se apagará en unos segundos...",
    "reboot": "Reiniciar SUNSCAN",
    "rebootConfirm": "¿Está seguro de que desea reiniciar su SUNSCAN?",
    "rebootOk": "Su SUNSCAN se reiniciará en unos segundos...",
    "currentVersion": "Versión actual",
    "newVersion": "Nueva versión disponible",
    "displayWatermark": "Mostrar marca de agua",
    "displayWatermarkDescription": "Muestra el logo de SUNSCAN y el nombre del observador en la esquina inferior izquierda de la imagen",
    "autoStopScan": "Parada automática del escaneo",
    "autoStopScanDescription": "Detiene la grabación 30 s después del tiempo de paso estimado del disco",
    "globalConfiguration": "Configuración global",
    "screenOrientation": "Orientación de pantalla",
    "screenOrientationDescription": "Auto: se adapta a la rotación del teléfono, o bloquea a una orientación específica",
    "cameraLeft": "Cámara Izquierda",
    "cameraRight": "Cámara Derecha",
    "stackingConfiguration": "Opciones de apilado",
    "patchSize": "Tamaño de parche",
    "stepSize": "Tamaño de paso",
    "intensityThreshold": "Umbral de intensidad",
    "reset": "Valores predeterminados",
    "resetView": "Restablecer vista",
    // status
    "sunscan": "SUNSCAN",
    "storage": "Almacenamiento",
    "freeStorage": "Libre",
    "camera": "Cámara",
    "connect": "Conectar",
    "disconnect": "Desconectar",
    "refresh": "Actualizar",
    "ipAddress": "Dirección IP",
    "backendApiVersion": "Versión API Backend",
    "debug": "Depuración",
    "security": "Seguridad",
    "hotspotMode": "Modo punto de acceso",
    "offlineMode": "Modo sin conexión",
    "updateFirmware": "Actualizar firmware",
    // picture screen
    "downloaded": "Descargado",
    "downloading": "Descargando",
    "downloadError": "Error de descarga",
    "download": "Descargar",
    "delete": "Eliminar",
    "deleteConfirm": "¿Está seguro de que desea eliminar este escaneo?",
    "deleteStackedConfirm": "¿Está seguro de que desea eliminar estas imágenes apiladas?",
    "deleteGenericConfirm": "¿Está seguro de que desea eliminar estos elementos?",
    "warning": "Advertencia",
    // scan screen
    "snapShot": "Instantánea",
    "color": "Color",
    "norm": "Normal",
    "adjust": "Ajustar",
    "grid": "Cuadrícula",
    "focus": "Enfoque",
    "focusMsg": "Puntuación de enfoque",
    "focusReset": "Reiniciar",
    "focusWaiting": "Midiendo la nitidez…",
    "focusBest": "mejor: {{value}}",
    "focusNewBest": "¡Nuevo máximo!",
    "focusStep1": "Centre el Sol en la rendija para que se vea lo más ancho posible.",
    "focusStep2": "Gire el enfoque de la lente frontal: la barra debe subir.",
    "focusStep3": "Pase ligeramente el pico (flecha roja) y vuelva hasta ~100 %.",
    "auto": "Auto",
    "advancedProcessing": "Procesamiento del escaneo",
    "advancedProcessingOptions": "Modo avanzado",
    "noiseReduction": "Reducción de ruido",
    "offset": "Desplazamiento",
    "dopplerShift": "Doppler (+/-)",
    "continuumShift": "Desplazamiento del continuo",
    "surfaceSharpenLevel": "Nivel de nitidez de imagen de superficie",
    "continuumSharpenLevel": "Nivel de nitidez de imagen del continuo",
    "protusSharpenLevel": "Nivel de nitidez de imagen de eclipse artificial",
    "Off": "Apagado",
    "Low": "Bajo",
    "Medium": "Medio",
    "High": "Alto",
    "startProcessing": "Iniciar procesamiento",
    "verticalProfile": "perfil vertical / enfoque de cámara",
    "horizontalProfile": "perfil horizontal / enfoque de telescopio",
    "verticalProfileTitle": "Espectro",
    "horizontalProfileTitle": "Continuo",
    "helium": "Procesamiento de helio",
    "scanCompleteTitle": "Escaneo completado",
    "otherLine": "Otra",
    "selectLineMessage": "Por favor, seleccione la línea correspondiente a su escaneo.",
    "dopplerColor": "Color Doppler",
    "orangeblue": "Naranja-Azul",
    "redblue": "Rojo-Azul",
    "doppler": "Calcular imagen Doppler",
    // scan info
    "typeImage": "Tipo de imagen",
    "acquisitionTime": "Tiempo de adquisición",
    "filePath": "Ruta del archivo",
    "scanPath": "Ruta de escaneo",
    "acquisitionSettings": "Configuración de adquisición",
    "camera": "Cámara",
    "exposure": "Exposición",
    "gain": "Ganancia",
    "processingLog": "Registro de procesamiento",
    "scanSelected": "escaneos seleccionados",
    "delete": "Eliminar",
    "stack": "Apilar",
    "animate": "Animar",
    // list screen
    "scans": "Escaneos",
    "stacked": "Apilados",
    "animations": "Animaciones",
    "snapshots": "Instantáneas",
    "processing": "Procesamiento en curso",
    // animation options modal
    "animationOptions": "Opciones de animación",
    "frameDuration": "Duración del fotograma (ms)",
    "displayDatetime": "Mostrar fecha y hora",
    "resizeGif": "Redimensionar GIF (50%)",
    "bidirectional": "Bidireccional",
    "addAverageFrame": "Añadir fotograma promedio",
    "startProcessing": "Iniciar procesamiento",
    "selectAtLeastOneItem": "Por favor seleccione al menos dos elementos",
    "disconnectCameraBeforeStacking": "Por favor desconecte la cámara antes de apilar imágenes",
    // settings sections
    "connectionSection": "Conexión",
    "deviceSection": "Dispositivo",
    "advancedSection": "Avanzado",
    "emptyGallery": "No hay nada que mostrar",
    // gallery line filter
    "filterCompleted": "Procesados",
    "filterPending": "Sin procesar",
    "filterFailed": "Con error",
    "filterToday": "Hoy",
    "filterWeek": "Últimos 7 días",
    "filterMonth": "Últimos 30 días",
    "filterClear": "Borrar filtros",
    "selectAll": "Seleccionar todo ({{count}})",
    "unselectAll": "Deseleccionar todo",
    "filterUntagged": "Sin línea",
    // processing steps (narration shown while a scan is processed)
    "stepReadingSer": "Leyendo el archivo SER",
    "stepMeanImage": "Calculando la imagen media",
    "stepDetectingLine": "Detectando la línea espectral",
    "stepPolynomialFit": "Ajustando el polinomio de curvatura",
    "stepReconstructing": "Reconstruyendo el disco solar",
    "stepTiltCorrection": "Corrigiendo inclinación y geometría",
    "stepScaling": "Escalando el disco",
    "stepCircleDetection": "Detectando el limbo y centrando",
    "stepSurface": "Generando la imagen de superficie",
    "stepContinuum": "Generando la imagen del continuo",
    "stepProtus": "Extrayendo las protuberancias",
    "stepDoppler": "Calculando la imagen Doppler",
    "stepClahe": "Mejorando el contraste (CLAHE)",
    "stepWatermark": "Aplicando la marca de agua",
    "stepSaving": "Guardando las imágenes",
    // live processing progress, published by the backend on scan_progress_<key>
    "processStepStarting": "Procesamiento en cola",
    "processStepReadingScan": "Leyendo el archivo SER",
    "processStepBuildingDisk": "Reconstruyendo el disco",
    "processStepCorrectingGeometry": "Corrigiendo la geometría",
    "processStepImageSurface": "Generando las imágenes de superficie",
    "processStepImageContinuum": "Generando la imagen del continuo",
    "processStepImageProminences": "Extrayendo las protuberancias",
    "processStepImageDoppler": "Calculando las imágenes Doppler",
    "processStepImageHelium": "Generando las imágenes de helio",
    "processStepImageHepsilon": "Generando las imágenes Hε",
    "processStepDone": "Terminado",
    "processStepGeneric": "Procesando",
    "processErrorFileNotFound": "Archivo SER no encontrado en el SUNSCAN",
    "processErrorReconstructionFailed": "No se pudo reconstruir el disco solar: barrido demasiado corto o sin Sol",
    "processErrorImageGenerationFailed": "El disco se reconstruyó, pero no se pudieron generar las imágenes",
    "processErrorGeneric": "El procesamiento falló",
    // se ofrece cuando un barrido ya procesado se etiqueta Ca II H
    "hepsilonReprocessTitle": "Imágenes Hε disponibles",
    "hepsilonReprocessMessage": "Un barrido Ca II H también contiene la línea Hε. Vuelva a procesarlo para obtener sus imágenes Hε.",
    "hepsilonReprocessAction": "Reprocesar",
    // ventana de suma de imágenes (stacking)
    "stackingTitle": "Sumando las imágenes",
    "stackingFrames": "{{number}} imágenes seleccionadas",
    "stackingElapsed": "Tiempo transcurrido: {{time}}",
    "stackingHint": "El SUNSCAN sigue trabajando aunque se cierre la app.",
    "stackingFailed": "La suma ha fallado",
    "stackingFailedHint": "Compruebe la conexión con el SUNSCAN e inténtelo de nuevo.",
    "animationTitle": "Creando la animación",
    "animationFailed": "La animación ha fallado",
    // avance publicado por el backend en job_progress_<job_id>
    "jobStepStarting": "Iniciando",
    "jobStepAligning": "Alineando el escaneo {{current}} / {{total}}",
    "jobStepWritingImages": "Creando las imágenes apiladas",
    "jobStepCreatingGif": "Creando el GIF {{current}} / {{total}}",
    "jobStepDone": "Terminado",
    "jobStepGeneric": "Procesando",
    "jobErrorBusy": "Ya hay un apilado en curso en el SUNSCAN. Espere a que termine.",
    "jobErrorMissingImages": "Algunos escaneos no tienen la imagen procesada necesaria (escaneo no procesado, o reprocesado en helio). No se ha creado nada.",
    "jobErrorStackingFailed": "El apilado ha fallado en el SUNSCAN.",
    "jobErrorAnimationFailed": "La creación de un GIF ha fallado en el SUNSCAN.",
    "jobErrorRequestFailed": "Compruebe la conexión con el SUNSCAN e inténtelo de nuevo.",
    "jobErrorGeneric": "Se ha producido un error en el SUNSCAN. Inténtelo de nuevo.",
    // asistente de alineacion del barrido
    "assistant": "Asist.",
    "shearAngle": "incl.",
    "quality_excellent": "Ventana ideal",
    "quality_good": "Buena ventana",
    "quality_fair": "Utilizable",
    "quality_poor": "Muy inclinado",
    "quality_impossible": "El disco no cabe",
    "assistantSunDown": "Sol bajo el horizonte",
    "assistantNoLocation": "Esperando una posición GPS para calcular el barrido",
    "assistantLocationDenied": "Ubicación denegada: el asistente necesita tu posición",
    "assistantLocationUnavailable": "Posición GPS no disponible",
    "assistantOpenSettings": "toca para abrir los ajustes",
    "assistantRetry": "toca para reintentar",
    "assistantNoSignal": "Centra el Sol en la rendija para iniciar la guía",
    "assistantShiftBy": "Lleva el disco a la marca ({{amount}})",
    "assistantReady": "En posición — deja salir el Sol aguas arriba y graba",
    "assistantArmed": "Sol fuera de la rendija, inicia el barrido ahora",
    "assistantWontFit": "El disco no cabe, acércate al mediodía solar",
    "assistantWindow": "mejor {{start}}–{{end}}",
    "assistantScanRemaining": "quedan ≈ {{seconds}} s",
    "assistantScanComplete": "Duración estimada alcanzada, puedes parar",
    "scanPreview": "vista previa del disco",
    "autoStopIn": "Parada automática en {{seconds}} s",
    "autoStopCancel": "toca para cancelar",
    // identificacion de las lineas espectrales
    "ident": "Ident.",
    "identStarting": "Iniciando…",
    "identSearching": "Localizando el espectro…",
    "identUnknown": "Espectro no reconocido",
    "identDark": "Poca luz : coloque el Sol sobre la rendija",
    "identSaturated": "Saturado : reduzca la exposición",
    "identFlat": "Ninguna línea visible : compruebe el enfoque",
    "identShort": "Espectro demasiado estrecho para identificarlo",
    "identSilent": "No se recibe ningún perfil del SUNSCAN",
    "identUnsupported": "Actualización del SUNSCAN necesaria",
    "identLines": "{{n}} líneas",
    "identSolar": "Sol",
    "identTelluric": "Atmósfera terrestre",
    // home wifi
    "wifiNetwork": "WiFi del SUNSCAN",
    "wifiModeHotspot": "Punto de acceso {{ssid}}",
    "wifiModeClient": "Conectado a {{ssid}} ({{ip}})",
    "wifiModeConnecting": "Conectando…",
    "wifiModeDisconnected": "Desconectado",
    "wifiConnectHome": "Conectar a mi WiFi",
    "wifiBackToHotspot": "Volver al punto de acceso",
    "wifiBackToHotspotConfirm": "El SUNSCAN volverá a su punto de acceso {{hotspot}} y se perderá la conexión. Las redes guardadas se conservan: en el próximo arranque, se conectará de nuevo a su WiFi si está a su alcance.",
    "wifiRejoinHotspot": "Conecte su teléfono a la red WiFi {{hotspot}}.",
    "wifiSavedNetworks": "Redes guardadas",
    "wifiSavedNetworksHint": "Se conecta automáticamente al arrancar si están a su alcance.",
    "wifiForget": "Olvidar",
    "wifiForgetConfirm": "¿Olvidar {{ssid}}? El SUNSCAN ya no se conectará a esta red.",
    "wifiForgetCurrentConfirm": "¿Olvidar {{ssid}}? El SUNSCAN está conectado a esta red: volverá a su punto de acceso {{hotspot}} y se perderá la conexión.",
    "wifiChooseNetwork": "Elija su red WiFi",
    "wifiScanning": "El SUNSCAN está buscando redes…",
    "wifiScanCached": "La búsqueda ha fallado, estos son los resultados anteriores.",
    "wifiRetry": "Reintentar",
    "wifiNoNetwork": "No se encontró ninguna red.",
    "wifiOtherNetwork": "Otra red…",
    "wifiUnsupported": "no compatible",
    "wifiSaved": "guardada",
    "wifiInUse": "actual",
    "wifiSsid": "Nombre de la red (SSID)",
    "wifiPassword": "Contraseña",
    "wifiPasswordOptional": "Contraseña (vacía si no tiene)",
    "wifiConnect": "Conectar",
    "wifiClose": "Cerrar",
    "wifiJoining": "El SUNSCAN se está conectando a {{ssid}}…",
    "wifiJoiningHint": "La conexión con el SUNSCAN se va a cortar, es normal.",
    "wifiPutPhoneOn": "Conecte ahora su teléfono a {{ssid}}.",
    "wifiOpenWifiSettings": "Abrir los ajustes WiFi",
    "wifiConnected": "SUNSCAN conectado a {{ssid}}",
    "wifiConnectedHint": "La aplicación lo alcanza ahora en {{url}}. Lejos de esta red, el SUNSCAN vuelve a activar su punto de acceso: active de nuevo el modo punto de acceso en los ajustes.",
    "wifiFailedHint": "El SUNSCAN ha vuelto a su punto de acceso {{hotspot}}.",
    "wifiLost": "SUNSCAN no encontrado",
    "wifiLostPhone": "Compruebe que su teléfono está en {{ssid}},",
    "wifiLostHotspot": "o vuelva a conectarlo al punto de acceso {{hotspot}}.",
    "wifiSearchAgain": "Buscar de nuevo",
    "wifiEnterIp": "Introducir la IP",
    "wifiUnreachable": "No se puede contactar con el SUNSCAN.",
    "wifiError_invalid_ssid": "Nombre de red no válido",
    "wifiError_invalid_password": "La contraseña debe tener entre 8 y 63 caracteres",
    "wifiError_unsupported_security": "Este tipo de red (WEP, empresarial) no es compatible",
    "wifiError_busy": "Ya hay una conexión en curso, inténtelo de nuevo en un minuto",
    "wifiError_not_supported": "Este SUNSCAN no puede conectarse a una red WiFi",
    "wifiError_wrong_password": "Contraseña incorrecta",
    "wifiError_network_not_found": "Red no encontrada (fuera de alcance o nombre mal escrito)",
    "wifiError_timeout": "La red no respondió a tiempo",
    "wifiError_no_address": "Conectado, pero el router no asignó ninguna dirección",
    "wifiError_connection_failed": "La conexión ha fallado",
    "manualExposureTitle": "Tiempo de exposición",
    "manualExposureRange": "Entre {{min}} y {{max}} ms",
    "apply": "Aplicar",
    "expTipTitle": "Ajuste de la exposición",
    "expTipTapLabel": "Toque corto en EXP",
    "expTipTapDetail": "Introducir el tiempo de exposición con el teclado, en milisegundos",
    "expTipLongPressLabel": "Pulsación larga en EXP",
    "expTipLongPressDetail": "Cambiar el rango de exposición: normal, corto (SE) o largo (LE)",
    "gotIt": "Entendido",
    "scanDetails": "Información",
    "menuLine": "Línea: {{line}}",
    "menuChooseLine": "Elegir la línea",
    "menuView3d": "Vista 3D",
    "lineModalTitle": "Línea del escaneo",
    "lineModalMessage": "Elija la línea observada durante este escaneo.",
    "lineModalTitleStack": "Línea del apilado",
    "lineModalMessageStack": "Elija la línea de los escaneos de este apilado. La marca de agua de la imagen suele indicarla.",
    "lineModalTitleAnimation": "Línea de la animación",
    "lineModalMessageAnimation": "Elija la línea de las imágenes de esta animación. La marca de agua suele indicarla.",
    "lineModalTitleMany": "Línea de la selección",
    "lineModalMessageMany": "La línea elegida reemplazará la de los elementos seleccionados ({{count}}).",
    "line": "Línea",
    "tagging": "Guardando...",
    "tagManyFailed": "No se pudo guardar la línea de algunos elementos ({{count}}).",
    "hubTipHotspot": "Envío no disponible: el SUNSCAN está en su hotspot, sin acceso a internet. Conéctelo a su WiFi.",
    "hubTipUnreachable": "Envío no disponible: SpectroSolHub no responde. ¿Tiene acceso a internet el WiFi del SUNSCAN?",
    // SpectroSolHub
    "hubViewOnHub": "Ver en SpectroSolHub",
    "hubAccount": "Cuenta",
    "hubDescription": "Comparta sus imágenes en la plataforma de la comunidad de espectroheliógrafos. El SUNSCAN realiza el envío: debe estar conectado a una red WiFi con internet.",
    "hubUsername": "Usuario de SpectroSolHub",
    "hubPassword": "Contraseña",
    "hubTotpHint": "Autenticación en dos pasos: introduzca el código de 6 dígitos de su aplicación.",
    "hubLogin": "Iniciar sesión",
    "hubLogout": "Cerrar sesión",
    "hubLogoutConfirm": "¿Desconectar la cuenta {{name}} del SUNSCAN? El token sigue apareciendo en su cuenta del sitio web, donde puede revocarlo.",
    "hubChangeAccount": "Usar otras credenciales",
    "hubPasswordNotKept": "La contraseña nunca se guarda: el SUNSCAN la cambia por un token de acceso.",
    "hubLoginPrompt": "Vincule el SUNSCAN a su cuenta de SpectroSolHub para enviar sus imágenes.",
    "hubConnectedAs": "Conectado como {{username}}",
    "hubChecking": "Comprobando la cuenta…",
    "hubQuota": "Espacio: {{storage}} · Imágenes: {{images}}",
    "hubNeedsInternet": "El SUNSCAN está en su hotspot, sin internet: conéctelo a su WiFi para enviar imágenes.",
    "hubImages": "Imágenes",
    "hubLine": "Línea",
    "hubLineUntagged": "Este escaneo no tiene línea: {{line}} es solo un valor por defecto. Elija la línea correcta o confirme.",
    "hubLineConfirm": "Confirmar",
    "hubTitle": "Título",
    "hubNotes": "Notas",
    "hubNotesPlaceholder": "Condiciones, instrumento… (opcional)",
    "hubPublish": "Publicar",
    "hubPublishHint": "La observación será pública",
    "hubDraftHint": "Borrador, visible solo para usted, publicable desde el sitio web",
    "hubAlreadySent": "Ya enviado el {{date}}.",
    "hubNewObservation": "Cada envío crea una nueva observación en el hub: la anterior no se reemplaza ni se elimina.",
    "hubSend": "Enviar a SpectroSolHub",
    "hubSendAgain": "Enviar de nuevo",
    "hubImageCount": "Imagen {{image}} / {{images}}",
    "hubRunsInBackground": "Puede cerrar esta ventana: el SUNSCAN sigue enviando.",
    "hubPublished": "Publicado en SpectroSolHub",
    "hubSentAsDraft": "Imágenes enviadas, observación en borrador",
    "hubDraftChosen": "Publíquela desde el sitio web cuando quiera.",
    "hubPublishRefused": "El hub rechazó la publicación. Publique la observación desde el sitio web.",
    "hubIncompleteDraft": "Quedó un borrador incompleto en el hub. Un nuevo envío creará otra observación.",
    "hubOpenObservation": "Ver la observación",
    "hubRetry": "Reintentar",
    "hubDeleteSentConfirm": "Este escaneo se envió a SpectroSolHub, pero solo están allí las imágenes JPEG elegidas. Los archivos SER, FITS y PNG de 16 bits se perderán definitivamente y el escaneo ya no podrá reprocesarse. ¿Eliminar?",
    "hubDeleteSentManyConfirm": "La selección incluye escaneos enviados a SpectroSolHub. Solo las imágenes JPEG elegidas al enviarlos están en el hub: los archivos SER, FITS y PNG de 16 bits se perderán definitivamente y estos escaneos ya no podrán reprocesarse. ¿Eliminar?",
    "hubDeleteSentItemConfirm": "Este elemento se envió a SpectroSolHub, pero solo están allí las imágenes elegidas en el envío. Los demás archivos, incluidos los PNG de 16 bits de un apilado, se perderán definitivamente. ¿Eliminar?",
    "hubDeleteSentItemsConfirm": "La selección incluye elementos enviados a SpectroSolHub. Solo las imágenes elegidas al enviarlos están en el hub: los demás archivos, incluidos los PNG de 16 bits de los apilados, se perderán definitivamente. ¿Eliminar?",
    "hubAnimationExperimental": "Experimental: el envío de animaciones (GIF) aún no se ha probado nunca en SpectroSolHub. Haga una primera prueba como borrador; si el hub lo rechaza, quedará un borrador vacío en su cuenta, que deberá eliminar desde el sitio.",
    "hubLineUnknown": "Línea desconocida: {{line}} es solo un valor por defecto. Elija la línea correcta o confirme.",
    "hubObservationDate": "Fecha de la observación (UTC)",
    "hubDatePlaceholder": "AAAA-MM-DD",
    "hubTimePlaceholder": "HH:MM",
    "hubObservationDateHint": "Rellenada con la fecha de creación, que puede diferir de la de la observación: compruébela en la marca de agua de las imágenes (toque la vista previa para ampliarla).",
    "filterHubSent": "En SpectroSolHub",
    "filterHubNotSent": "Aún no enviados",
    "hubStep_starting": "Iniciando",
    "hubStep_checking_account": "Comprobando la cuenta",
    "hubStep_creating_session": "Creando la observación",
    "hubStep_uploading_images": "Enviando las imágenes",
    "hubStep_publishing": "Publicando",
    "hubStep_done": "Terminado",
    "hubStep_generic": "Enviando",
    "hubError_missing_credentials": "Introduzca su usuario y contraseña",
    "hubError_invalid_credentials": "Usuario o contraseña incorrectos",
    "hubError_totp_required": "Se requiere el código de autenticación en dos pasos",
    "hubError_invalid_totp": "Código de autenticación rechazado",
    "hubError_hub_unreachable": "SpectroSolHub inaccesible: ¿tiene el SUNSCAN acceso a internet?",
    "hubError_hub_rejected": "El hub rechazó la solicitud",
    "hubError_hub_error": "El hub tiene un problema, inténtelo más tarde",
    "hubError_token_expired": "La sesión ha caducado: vuelva a iniciar sesión y reenvíe",
    "hubError_not_connected": "Ninguna cuenta de SpectroSolHub en el SUNSCAN",
    "hubError_busy": "Otro envío está en curso en el SUNSCAN",
    "hubError_processing_in_progress": "El escaneo se está procesando, espere",
    "hubError_not_processed": "Este escaneo aún no se ha procesado",
    "hubError_invalid_image": "Una imagen elegida ya no existe para este escaneo",
    "hubError_no_image": "Elija al menos una imagen",
    "hubError_invalid_line": "Línea desconocida para el hub",
    "hubError_invalid_path": "Escaneo no válido",
    "hubError_missing_observation_date": "Indique la fecha y la hora de la observación",
    "hubError_invalid_observation_date": "Fecha no válida: AAAA-MM-DD y HH:MM, en UTC, no en el futuro",
    "hubError_file_not_found": "Escaneo no encontrado en el SUNSCAN",
    "hubError_quota_exceeded": "No queda espacio suficiente en su cuenta de SpectroSolHub",
    "hubError_upload_failed": "El envío falló en el SUNSCAN",
    "hubError_request_failed": "No se puede contactar con el SUNSCAN",
    "hubError_generic": "El envío falló",
}
