export default {
    "language": "Idioma",
    "locale": "es-ES",
    "cancel": "Cancelar",
    // home
    "connectCamera": "Conectar cámara",
    "disconnectCamera": "Desconectar cámara",
    "observer": "Observador",
    "ipAddress": "Dirección IP",
    "storage": "Almacenamiento",
    "freeStorage": "libre",
    "totalStorage": "Total",
    "backendApiVersion": "Versión API Backend",
    "longitude": "Longitud",
    "latitude": "Latitud",
    "altitude": "Altitud",
    "sunrise": "Salida",
    "sunset": "Puesta",
    "transit": "Tránsito",
    "sun": "Sol",
    "cameraNotConnected": "Cámara no conectada",
    "simulated": "simulado",
    "cropRequiredTitle" : "Recorte primero la ventana",
    "cropRequiredMsg" : "Pulse el botón de recorte para pasar al modo escaneo y luego inicie la adquisición.",
    "lowStorageWarning": "Poco espacio de almacenamiento, por favor libere espacio antes de iniciar un nuevo escaneo",
    "storageCleanupHint": "Hora de limpiar sus escaneos",
    // settings
    "configuration": "Configuración",
    "debugMode": "Modo de depuración",
    "debugDescription": "Activa la visualización de registros de procesamiento y funciones de depuración.",
    "hotspotMode": "Modo punto de acceso",
    "hotspotDescription": "Por defecto, conéctese a la red wifi SUNSCAN.",
    "updateFirmware": "Actualizar firmware",
    "updateFirmwareDescription": "Hay una actualización del firmware disponible.",
    "security": "Seguridad",
    "securityDescription": "Si está habilitado, SUNSCAN solo se encenderá después de un toque corto en el dispositivo y un toque largo (5s) en el botón.",
    "offlineMode": "Modo sin conexión",
    "offlineDescription": "Fuerza la visualización de los controles de la cámara incluso si SUNSCAN no está conectado.",
    "sunscanIP": "IP de SUNSCAN",
    "sunscanIPDescription": "Modo punto de acceso desactivado, por favor ingrese aquí la IP de su SUNSCAN.",
    "searchSunscan": "Buscar el SUNSCAN",
    "searching": "Buscando",
    "sunscanFound": "SUNSCAN encontrado en {{url}}",
    "sunscanNotFound": "No se encontró ningún SUNSCAN en esta red. Compruebe que su SUNSCAN esté encendido y conectado a la misma red wifi que su teléfono, o introduzca su dirección IP manualmente.",
    "success": "Éxito",
    "update": "Actualizar",
    "clearImageCache": "Limpiar caché de imágenes",
    "clearCacheDescription": "Limpia la caché de imágenes para liberar espacio.",
    "updateFirmwareconfirm": "¿Está seguro de que desea actualizar el firmware? Se recomienda encender su SUNSCAN durante la actualización.",
    "firmwareIsOutdated": "Su firmware está desactualizado, por favor actualice el firmware en la configuración de la aplicación",
    "upToDate": "Tiene la última versión",
    "firmwarePostUpdateMessage": "El firmware ha sido actualizado, por favor reinicie la aplicación y su SUNSCAN para aplicar los cambios",
    "firmwareUpdating": "Actualizando...",
    "firmwareUpdateUnconfirmed": "No se pudo confirmar la actualización del firmware. Compruebe que su SUNSCAN está encendido y conectado, reinícielo e inténtelo de nuevo.",
    "clearCacheConfirm": "¿Está seguro de que desea limpiar la caché de imágenes?",
    "shutdown": "Apagar SUNSCAN",
    "shutdownConfirm": "¿Está seguro de que desea apagar su SUNSCAN?",
    "shutdownOk": "Su SUNSCAN se apagará en unos segundos...",
    "reboot": "Reiniciar SUNSCAN",
    "rebootConfirm": "¿Está seguro de que desea reiniciar su SUNSCAN?",
    "rebootOk": "Su SUNSCAN se reiniciará en unos segundos...",
    "currentVersion": "Versión actual",
    "newVersion": "Nueva versión disponible",
    "displayWatermark": "Mostrar marca de agua",
    "displayWatermarkDescription": "Muestra el logo de SUNSCAN y el nombre del observador en la esquina inferior izquierda de la imagen",
    "globalConfiguration": "Configuración global",
    "screenOrientation": "Orientación de pantalla",
    "screenOrientationDescription": "Auto: se adapta a la rotación del teléfono, o bloquea a una orientación específica",
    "cameraLeft": "Cámara Izquierda",
    "cameraRight": "Cámara Derecha",
    "stackingConfiguration": "Opciones de apilado",
    "patchSize": "Tamaño de parche",
    "stepSize": "Tamaño de paso",
    "intensityThreshold": "Umbral de intensidad",
    "reset": "Valores predeterminados",
    "resetView": "Restablecer vista",
    // status
    "sunscan": "SUNSCAN",
    "storage": "Almacenamiento",
    "freeStorage": "Libre",
    "camera": "Cámara",
    "connect": "Conectar",
    "disconnect": "Desconectar",
    "refresh": "Actualizar",
    "ipAddress": "Dirección IP",
    "backendApiVersion": "Versión API Backend",
    "debug": "Depuración",
    "security": "Seguridad",
    "hotspotMode": "Modo punto de acceso",
    "offlineMode": "Modo sin conexión",
    "updateFirmware": "Actualizar firmware",
    // picture screen
    "downloaded": "Descargado",
    "downloading": "Descargando",
    "downloadError": "Error de descarga",
    "download": "Descargar",
    "delete": "Eliminar",
    "deleteConfirm": "¿Está seguro de que desea eliminar este escaneo?",
    "deleteStackedConfirm": "¿Está seguro de que desea eliminar estas imágenes apiladas?",
    "deleteGenericConfirm": "¿Está seguro de que desea eliminar estos elementos?",
    "warning": "Advertencia",
    // scan screen
    "snapShot": "Instantánea",
    "color": "Color",
    "norm": "Normal",
    "adjust": "Ajustar",
    "grid": "Cuadrícula",
    "focus": "Enfoque",
    "focusMsg": "Puntuación de enfoque",
    "focusReset": "Reiniciar",
    "focusWaiting": "Midiendo la nitidez…",
    "focusBest": "mejor: {{value}}",
    "focusNewBest": "¡Nuevo máximo!",
    "focusStep1": "Centre el Sol en la rendija para que se vea lo más ancho posible.",
    "focusStep2": "Gire el enfoque de la lente frontal: la barra debe subir.",
    "focusStep3": "Pase ligeramente el pico (flecha roja) y vuelva hasta ~100 %.",
    "auto": "Auto",
    "advancedProcessing": "Procesamiento avanzado de escaneo",
    "advancedProcessingOptions": "Modo avanzado",
    "noiseReduction": "Reducción de ruido",
    "offset": "Desplazamiento",
    "dopplerShift": "Doppler (+/-)",
    "continuumShift": "Desplazamiento del continuo",
    "surfaceSharpenLevel": "Nivel de nitidez de imagen de superficie",
    "continuumSharpenLevel": "Nivel de nitidez de imagen del continuo",
    "protusSharpenLevel": "Nivel de nitidez de imagen de eclipse artificial",
    "Off": "Apagado",
    "Low": "Bajo",
    "Medium": "Medio",
    "High": "Alto",
    "startProcessing": "Iniciar procesamiento",
    "verticalProfile": "perfil vertical / enfoque de cámara",
    "horizontalProfile": "perfil horizontal / enfoque de telescopio",
    "verticalProfileTitle": "Espectro",
    "horizontalProfileTitle": "Continuo",
    "helium": "Procesamiento de helio",
    "scanCompleteTitle": "Escaneo completado",
    "otherLine": "Otra",
    "selectLineMessage": "Por favor, seleccione la línea correspondiente a su escaneo.",
    "dopplerColor": "Color Doppler",
    "orangeblue": "Naranja-Azul",
    "redblue": "Rojo-Azul",
    "doppler": "Calcular imagen Doppler",
    // scan info
    "typeImage": "Tipo de imagen",
    "acquisitionTime": "Tiempo de adquisición",
    "filePath": "Ruta del archivo",
    "scanPath": "Ruta de escaneo",
    "acquisitionSettings": "Configuración de adquisición",
    "camera": "Cámara",
    "exposure": "Exposición",
    "gain": "Ganancia",
    "processingLog": "Registro de procesamiento",
    "scanSelected": "escaneos seleccionados",
    "delete": "Eliminar",
    "stack": "Apilar",
    "animate": "Animar",
    // list screen
    "scans": "Escaneos",
    "stacked": "Apilados",
    "animations": "Animaciones",
    "snapshots": "Instantáneas",
    "processing": "Procesamiento en curso",
    // animation options modal
    "animationOptions": "Opciones de animación",
    "frameDuration": "Duración del fotograma (ms)",
    "displayDatetime": "Mostrar fecha y hora",
    "resizeGif": "Redimensionar GIF (50%)",
    "bidirectional": "Bidireccional",
    "addAverageFrame": "Añadir fotograma promedio",
    "startProcessing": "Iniciar procesamiento",
    "selectAtLeastOneItem": "Por favor seleccione al menos dos elementos",
    "disconnectCameraBeforeStacking": "Por favor desconecte la cámara antes de apilar imágenes",
    // settings sections
    "connectionSection": "Conexión",
    "deviceSection": "Dispositivo",
    "advancedSection": "Avanzado",
    "emptyGallery": "No hay nada que mostrar",
    // processing steps (narration shown while a scan is processed)
    "stepReadingSer": "Leyendo el archivo SER",
    "stepMeanImage": "Calculando la imagen media",
    "stepDetectingLine": "Detectando la línea espectral",
    "stepPolynomialFit": "Ajustando el polinomio de curvatura",
    "stepReconstructing": "Reconstruyendo el disco solar",
    "stepTiltCorrection": "Corrigiendo inclinación y geometría",
    "stepScaling": "Escalando el disco",
    "stepCircleDetection": "Detectando el limbo y centrando",
    "stepSurface": "Generando la imagen de superficie",
    "stepContinuum": "Generando la imagen del continuo",
    "stepProtus": "Extrayendo las protuberancias",
    "stepDoppler": "Calculando la imagen Doppler",
    "stepClahe": "Mejorando el contraste (CLAHE)",
    "stepWatermark": "Aplicando la marca de agua",
    "stepSaving": "Guardando las imágenes",
    // live processing progress, published by the backend on scan_progress_<key>
    "processStepStarting": "Procesamiento en cola",
    "processStepReadingScan": "Leyendo el archivo SER",
    "processStepBuildingDisk": "Reconstruyendo el disco",
    "processStepCorrectingGeometry": "Corrigiendo la geometría",
    "processStepImageSurface": "Generando las imágenes de superficie",
    "processStepImageContinuum": "Generando la imagen del continuo",
    "processStepImageProminences": "Extrayendo las protuberancias",
    "processStepImageDoppler": "Calculando las imágenes Doppler",
    "processStepImageHelium": "Generando las imágenes de helio",
    "processStepDone": "Terminado",
    "processStepGeneric": "Procesando",
    "processErrorFileNotFound": "Archivo SER no encontrado en el SUNSCAN",
    "processErrorReconstructionFailed": "No se pudo reconstruir el disco solar: barrido demasiado corto o sin Sol",
    "processErrorImageGenerationFailed": "El disco se reconstruyó, pero no se pudieron generar las imágenes",
    "processErrorGeneric": "El procesamiento falló",
    // ventana de suma de imágenes (stacking)
    "stackingTitle": "Sumando las imágenes",
    "stackingFrames": "{{number}} imágenes seleccionadas",
    "stackingElapsed": "Tiempo transcurrido: {{time}}",
    "stackingHint": "El SUNSCAN no informa de su avance. No salga de esta pantalla.",
    "stackingFailed": "La suma ha fallado",
    "stackingFailedHint": "Compruebe la conexión con el SUNSCAN e inténtelo de nuevo.",
    // asistente de alineacion del barrido
    "assistant": "Asist.",
    "shearAngle": "incl.",
    "quality_excellent": "Ventana ideal",
    "quality_good": "Buena ventana",
    "quality_fair": "Utilizable",
    "quality_poor": "Muy inclinado",
    "quality_impossible": "El disco no cabe",
    "assistantSunDown": "Sol bajo el horizonte",
    "assistantNoLocation": "Esperando una posición GPS para calcular el barrido",
    "assistantLocationDenied": "Ubicación denegada: el asistente necesita tu posición",
    "assistantLocationUnavailable": "Posición GPS no disponible",
    "assistantOpenSettings": "toca para abrir los ajustes",
    "assistantRetry": "toca para reintentar",
    "assistantNoSignal": "Centra el Sol en la rendija para iniciar la guía",
    "assistantShiftBy": "Lleva el disco a la marca ({{amount}})",
    "assistantReady": "En posición — deja salir el Sol aguas arriba y graba",
    "assistantArmed": "Sol fuera de la rendija, inicia el barrido ahora",
    "assistantWontFit": "El disco no cabe, acércate al mediodía solar",
    "assistantWindow": "mejor {{start}}–{{end}}",
    "assistantScanRemaining": "quedan ≈ {{seconds}} s",
    "assistantScanComplete": "El disco ha terminado de pasar, puedes parar",
    "scanPreview": "vista previa del disco",
    "autoStopIn": "Parada automática en {{seconds}} s",
    "autoStopCancel": "toca para cancelar",
    // identificacion de las lineas espectrales
    "ident": "Ident.",
    "identStarting": "Iniciando…",
    "identSearching": "Localizando el espectro…",
    "identUnknown": "Espectro no reconocido",
    "identDark": "Poca luz : coloque el Sol sobre la rendija",
    "identSaturated": "Saturado : reduzca la exposición",
    "identFlat": "Ninguna línea visible : compruebe el enfoque",
    "identShort": "Espectro demasiado estrecho para identificarlo",
    "identSilent": "No se recibe ningún perfil del SUNSCAN",
    "identUnsupported": "Actualización del SUNSCAN necesaria",
    "identLines": "{{n}} líneas",
    "identSolar": "Sol",
    "identTelluric": "Atmósfera terrestre",
    // home wifi
    "wifiNetwork": "WiFi del SUNSCAN",
    "wifiModeHotspot": "Punto de acceso {{ssid}}",
    "wifiModeClient": "Conectado a {{ssid}} ({{ip}})",
    "wifiModeConnecting": "Conectando…",
    "wifiModeDisconnected": "Desconectado",
    "wifiConnectHome": "Conectar a mi WiFi",
    "wifiBackToHotspot": "Volver al punto de acceso",
    "wifiBackToHotspotConfirm": "El SUNSCAN volverá a su punto de acceso {{hotspot}} y se perderá la conexión. Las redes guardadas se conservan: en el próximo arranque, se conectará de nuevo a su WiFi si está a su alcance.",
    "wifiRejoinHotspot": "Conecte su teléfono a la red WiFi {{hotspot}}.",
    "wifiSavedNetworks": "Redes guardadas",
    "wifiSavedNetworksHint": "Se conecta automáticamente al arrancar si están a su alcance.",
    "wifiForget": "Olvidar",
    "wifiForgetConfirm": "¿Olvidar {{ssid}}? El SUNSCAN ya no se conectará a esta red.",
    "wifiForgetCurrentConfirm": "¿Olvidar {{ssid}}? El SUNSCAN está conectado a esta red: volverá a su punto de acceso {{hotspot}} y se perderá la conexión.",
    "wifiChooseNetwork": "Elija su red WiFi",
    "wifiScanning": "El SUNSCAN está buscando redes…",
    "wifiScanCached": "La búsqueda ha fallado, estos son los resultados anteriores.",
    "wifiRetry": "Reintentar",
    "wifiNoNetwork": "No se encontró ninguna red.",
    "wifiOtherNetwork": "Otra red…",
    "wifiUnsupported": "no compatible",
    "wifiSaved": "guardada",
    "wifiInUse": "actual",
    "wifiSsid": "Nombre de la red (SSID)",
    "wifiPassword": "Contraseña",
    "wifiPasswordOptional": "Contraseña (vacía si no tiene)",
    "wifiConnect": "Conectar",
    "wifiClose": "Cerrar",
    "wifiJoining": "El SUNSCAN se está conectando a {{ssid}}…",
    "wifiJoiningHint": "La conexión con el SUNSCAN se va a cortar, es normal.",
    "wifiPutPhoneOn": "Conecte ahora su teléfono a {{ssid}}.",
    "wifiOpenWifiSettings": "Abrir los ajustes WiFi",
    "wifiConnected": "SUNSCAN conectado a {{ssid}}",
    "wifiConnectedHint": "La aplicación lo alcanza ahora en {{url}}. Lejos de esta red, el SUNSCAN vuelve a activar su punto de acceso: active de nuevo el modo punto de acceso en los ajustes.",
    "wifiFailedHint": "El SUNSCAN ha vuelto a su punto de acceso {{hotspot}}.",
    "wifiLost": "SUNSCAN no encontrado",
    "wifiLostPhone": "Compruebe que su teléfono está en {{ssid}},",
    "wifiLostHotspot": "o vuelva a conectarlo al punto de acceso {{hotspot}}.",
    "wifiSearchAgain": "Buscar de nuevo",
    "wifiEnterIp": "Introducir la IP",
    "wifiUnreachable": "No se puede contactar con el SUNSCAN.",
    "wifiError_invalid_ssid": "Nombre de red no válido",
    "wifiError_invalid_password": "La contraseña debe tener entre 8 y 63 caracteres",
    "wifiError_unsupported_security": "Este tipo de red (WEP, empresarial) no es compatible",
    "wifiError_busy": "Ya hay una conexión en curso, inténtelo de nuevo en un minuto",
    "wifiError_not_supported": "Este SUNSCAN no puede conectarse a una red WiFi",
    "wifiError_wrong_password": "Contraseña incorrecta",
    "wifiError_network_not_found": "Red no encontrada (fuera de alcance o nombre mal escrito)",
    "wifiError_timeout": "La red no respondió a tiempo",
    "wifiError_no_address": "Conectado, pero el router no asignó ninguna dirección",
    "wifiError_connection_failed": "La conexión ha fallado",
}
