export default {
    "language": "Language",
    "locale": "en-GB",
    "cancel": "Cancel",
    // home
    "connectCamera" : "Connect Camera",
    "disconnectCamera" : "Disconnect Camera",
    "observer" : "Observer",
    "ipAddress" : "IP Address",
    "storage" : "Storage",
    "freeStorage" : "free",
    "totalStorage" : "Total",
    "backendApiVersion" : "Backend API Version",
    "longitude" : "Longitude",
    "latitude" : "Latitude",
    "altitude" : "Altitude",
    "sunrise" : "Rise",
    "sunset" : "Set",
    "transit" : "Transit",
    "sun" : "Sun",
    "lowStorageWarning" : "Low storage space, please free up some space before starting a new scan",
    // settings
    "configuration": "Settings",
    "debugMode": "Debug mode",
    "debugDescription": "Enables the display of processing logs and debug functions.",
    "hotspotMode": "Hotspot mode",
    "hotspotDescription": "Default, connect to the SUNSCAN wifi network.",
    "updateFirmware": "Update firmware",
    "updateFirmwareDescription": "An update of the firmware is available.",
    "security": "Security",
    "securityDescription": "If enabled, SUNSCAN will only be turned on after a short tap on the device and a long tap (5s) on the button.",
    "offlineMode": "Offline mode",
    "offlineDescription": "Force the display of camera controls even if SUNSCAN is not connected.",
    "sunscanIP": "SUNSCAN IP",
    "sunscanIPDescription": "Hotspot mode disabled, please enter the IP of your SUNSCAN here.",
    "update": "Update",
    "clearImageCache": "Clear image cache",
    "clearCacheDescription": "Clears the image cache to free up space.",
    "updateFirmwareconfirm": "Are you sure you want to update the firmware?",
    "firmwareIsOutdated": "Your firmware is outdated, please update the firmware in the application settings",
    "upToDate": "You have the latest version",
    "firmwarePostUpdateMessage": "The firmware has been updated, please restart the application and your SUNSCAN to apply the changes",
    "clearCacheConfirm": "Are you sure you want to clear the image cache?",
    "shutdown": "Shutdown SUNSCAN",
    "shutdownConfirm": "Are you sure you want to shutdown your SUNSCAN?",
    "shutdownOk": "Your SUNSCAN will shutdown in a few seconds...",
    "reboot": "Reboot SUNSCAN",
    "rebootConfirm": "Are you sure you want to reboot your SUNSCAN?",
    "rebootOk": "Your SUNSCAN will reboot in a few seconds...",
    // picture screen
    "downloaded": "Downloaded",
    "downloading": "Downloading",
    "download": "Download",
    "delete": "Delete",
    "deleteConfirm": "Are you sure you want to delete this scan?",
    "warning": "Warning",
    // scan screen
    "snapShot": "Snapshot",
    "color": "Color",
    "norm": "Norm",
    "adjust": "Adjust",
    "grid": "Grid",
    "auto": "Auto",
    "advancedProcessing":"Scan processing",
    "advancedProcessingOptions":"Advanced mode",
    "noiseReduction":"Noise reduction",
    "offset":"Offset",
    "dopplerShift":"Doppler (+/-)",
    "continuumShift":"Continuum shift",
    "surfaceSharpenLevel":"Surface image sharpen level",
    "continuumSharpenLevel":"Continuum image sharpen level",
    "protusSharpenLevel":"Artificial eclipse image sharpen level",
    "Off":"Off",
    "Low":"Low",
    "Medium":"Medium",
    "High":"High",
    "startProcessing": "Start processing",
    "pleaseWait": "The processing may take several minutes...",
    // scan info
    "typeImage": "Type of image",
    "acquisitionTime": "Acquisition time",
    "filePath": "File path",
    "scanPath": "Scan path",
    "acquisitionSettings": "Acquisition settings",
    "camera": "Camera",
    "exposure": "Exposure",
    "gain": "Gain",
    "processingLog": "Processing log",
}