export default {
    "language": "Language",
    "locale": "en-GB",
    "cancel": "Cancel",
    // home
    "connectCamera" : "Connect Camera",
    "disconnectCamera" : "Disconnect Camera",
    "observer" : "Observer",
    "ipAddress" : "IP Address",
    "storage" : "Storage",
    "freeStorage" : "free",
    "totalStorage" : "Total",
    "backendApiVersion" : "Backend API Version",
    "longitude" : "Longitude",
    "latitude" : "Latitude",
    "altitude" : "Altitude",
    "sunrise" : "Rise",
    "sunset" : "Set",
    "transit" : "Transit",
    "sun" : "Sun",
    "cameraNotConnected" : "Camera not connected",
    "simulated" : "simulated",
    "cropRequiredTitle" : "Crop the frame first",
    "cropRequiredMsg" : "Tap the crop button to switch to scan mode, then start the acquisition.",
    "lowStorageWarning" : "Low storage space, please free up some space before starting a new scan",
    "storageCleanupHint" : "Time to clean up your scans",
    // settings
    "configuration": "Settings",
    "debugMode": "Debug mode",
    "debugDescription": "Enables the display of processing logs and debug functions.",
    "hotspotMode": "Hotspot mode",
    "hotspotDescription": "Default, connect to the SUNSCAN wifi network.",
    "updateFirmware": "Update firmware",
    "updateFirmwareDescription": "An update of the firmware is available.",
    "security": "Security",
    "securityDescription": "If enabled, SUNSCAN will only be turned on after a short tap on the device and a long tap (5s) on the button.",
    "offlineMode": "Offline mode",
    "offlineDescription": "Force the display of camera controls even if SUNSCAN is not connected.",
    "sunscanIP": "SUNSCAN IP",
    "sunscanIPDescription": "Hotspot mode disabled, please enter the IP of your SUNSCAN here.",
    "searchSunscan": "Search for SUNSCAN",
    "searching": "Searching",
    "sunscanFound": "SUNSCAN found at {{url}}",
    "sunscanNotFound": "No SUNSCAN found on this network. Check that your SUNSCAN is powered on and connected to the same wifi network as your phone, or enter its IP address manually.",
    "success": "Success",
    "update": "Update",
    "clearImageCache": "Clear image cache",
    "clearCacheDescription": "Clears the image cache to free up space.",
    "updateFirmwareconfirm": "Are you sure you want to update the firmware? It is recommended to power on your SUNSCAN while updating.",
    "firmwareIsOutdated": "Your firmware is outdated, please update the firmware in the application settings",
    "upToDate": "You have the latest version",
    "firmwarePostUpdateMessage": "The firmware has been updated, please restart the application and your SUNSCAN to apply the changes",
    "firmwareUpdating": "Updating...",
    "firmwareUpdateUnconfirmed": "Could not confirm the firmware update. Check that your SUNSCAN is powered on and connected, restart it, then try again.",
    "clearCacheConfirm": "Are you sure you want to clear the image cache?",
    "shutdown": "Shutdown SUNSCAN",
    "shutdownConfirm": "Are you sure you want to shutdown your SUNSCAN?",
    "shutdownOk": "Your SUNSCAN will shutdown in a few seconds...",
    "reboot": "Reboot SUNSCAN",
    "rebootConfirm": "Are you sure you want to reboot your SUNSCAN?",
    "rebootOk": "Your SUNSCAN will reboot in a few seconds...",
    "currentVersion": "Current version",
    "newVersion": "New version available",
    "displayWatermark": "Display watermark",
    "displayWatermarkDescription": "Displays the SUNSCAN logo and observer name on the bottom left corner of the image",
    "globalConfiguration": "Global configuration",
    "screenOrientation": "Screen orientation",
    "screenOrientationDescription": "Auto: adapts to phone rotation, or lock to a specific orientation",
    "cameraLeft": "Camera Left",
    "cameraRight": "Camera Right",
    "stackingConfiguration": "Stacking options",
    "patchSize": "Patch size",
    "stepSize": "Step size",
    "intensityThreshold": "Intensity threshold",
    "reset": "Valeurs par défaut",
    "resetView": "Reset view",
    // status
    "sunscan": "SUNSCAN",
    "storage": "Storage",
    "freeStorage": "Free",
    "camera": "Camera",
    "connect": "Connect",
    "disconnect": "Disconnect",
    "refresh": "Refresh",
    "ipAddress": "IP Address",
    "backendApiVersion": "Backend API Version",
    "debug": "Debug",
    "security": "Security",
    "hotspotMode": "Hotspot mode",
    "offlineMode": "Offline mode",
    "updateFirmware": "Update firmware",
    // picture screen
    "downloaded": "Downloaded",
    "downloading": "Downloading",
    "downloadError": "Download failed",
    "download": "Download",
    "delete": "Delete",
    "deleteConfirm": "Are you sure you want to delete this scan?",
    "deleteStackedConfirm": "Are you sure you want to delete this stacked images?",
    "deleteGenericConfirm": "Are you sure you want to delete these items?",
    "warning": "Warning",
    // scan screen
    "snapShot": "Snapshot",
    "color": "Color",
    "norm": "Norm",
    "adjust": "Adjust",
    "grid": "Grid",
    "focus": "Focus",
    "focusMsg": "Focus score",
    "focusReset": "Reset",
    "focusWaiting": "Measuring sharpness…",
    "focusBest": "best: {{value}}",
    "focusNewBest": "New best!",
    "focusStep1": "Center the Sun on the slit so that it looks as wide as possible.",
    "focusStep2": "Turn the focuser of the front lens: the bar should rise.",
    "focusStep3": "Go slightly past the peak (red arrow), then come back to ~100%.",
    "auto": "Auto",
    "advancedProcessing":"Advanced scan processing",
    "advancedProcessingOptions":"Advanced mode",
    "noiseReduction":"Noise reduction",
    "offset":"Offset",
    "dopplerShift":"Doppler (+/-)",
    "continuumShift":"Continuum shift",
    "surfaceSharpenLevel":"Surface image sharpen level",
    "continuumSharpenLevel":"Continuum image sharpen level",
    "protusSharpenLevel":"Artificial eclipse image sharpen level",
    "Off":"Off",
    "Low":"Low",
    "Medium":"Medium",
    "High":"High",
    "startProcessing": "Start processing",
    "verticalProfile" : "vertical profile / camera focus",
    "horizontalProfile":"horizontal profile / telescope focus",
    "verticalProfileTitle" : "Spectrum",
    "horizontalProfileTitle":"Continuum",
    "helium": "Helium processing",
    "scanCompleteTitle": "Scan complete",
    "otherLine": "Other",
    "selectLineMessage": "Please, select the line corresponding to your scan.",
    "dopplerColor": "Doppler color",
    "orangeblue": "Orange-Blue",
    "redblue": "Red-Blue",
    "doppler": "Calculate Doppler image",
    // scan info
    "typeImage": "Type of image",
    "acquisitionTime": "Acquisition time",
    "filePath": "File path",
    "scanPath": "Scan path",
    "acquisitionSettings": "Acquisition settings",
    "camera": "Camera",
    "exposure": "Exposure",
    "gain": "Gain",
    "processingLog": "Processing log",
    "scanSelected": "scans selected",
    "delete": "Delete",
    "stack": "Stack",
    "animate": "Animate",
    // list screen
    "scans": "Scans",
    "stacked": "Stacked",
    "animations": "Animations",
    "snapshots": "Snapshots",
    "processing": "Processing in progress",
    // animation options modal
    "animationOptions": "Animation options",
    "frameDuration": "Frame duration (ms)",
    "displayDatetime": "Display datetime",
    "resizeGif": "Resize GIF (50%)",
    "bidirectional": "Bidirectional",
    "addAverageFrame": "Add average frame",
    "startProcessing": "Start processing",
    "selectAtLeastOneItem": "Please select at least two items",
    "disconnectCameraBeforeStacking" : "Please disconnect the camera before stacking images",
    // settings sections
    "connectionSection": "Connection",
    "deviceSection": "Device",
    "advancedSection": "Advanced",
    "emptyGallery": "Nothing to show yet",
    // processing steps (narration shown while a scan is processed)
    "stepReadingSer": "Reading the SER file",
    "stepMeanImage": "Computing the mean image",
    "stepDetectingLine": "Detecting the spectral line",
    "stepPolynomialFit": "Fitting the curvature polynomial",
    "stepReconstructing": "Reconstructing the solar disk",
    "stepTiltCorrection": "Correcting tilt and geometry",
    "stepScaling": "Scaling the disk",
    "stepCircleDetection": "Detecting the limb and centring",
    "stepSurface": "Building the surface image",
    "stepContinuum": "Building the continuum image",
    "stepProtus": "Extracting the prominences",
    "stepDoppler": "Computing the Doppler image",
    "stepClahe": "Enhancing contrast (CLAHE)",
    "stepWatermark": "Applying the watermark",
    "stepSaving": "Saving the images",
    // live processing progress, published by the backend on scan_progress_<key>
    "processStepStarting": "Processing queued",
    "processStepReadingScan": "Reading the SER file",
    "processStepBuildingDisk": "Reconstructing the disk",
    "processStepCorrectingGeometry": "Correcting the geometry",
    "processStepImageSurface": "Building the surface images",
    "processStepImageContinuum": "Building the continuum image",
    "processStepImageProminences": "Extracting the prominences",
    "processStepImageDoppler": "Computing the Doppler images",
    "processStepImageHelium": "Building the helium images",
    "processStepDone": "Done",
    "processStepGeneric": "Processing",
    "processErrorFileNotFound": "SER file not found on the SUNSCAN",
    "processErrorReconstructionFailed": "The solar disk could not be reconstructed: scan too short, or no Sun",
    "processErrorImageGenerationFailed": "The disk was reconstructed, but the images could not be generated",
    "processErrorGeneric": "Processing failed",
    // frame stacking pop-in
    "stackingTitle": "Stacking the frames",
    "stackingFrames": "{{number}} frames selected",
    "stackingElapsed": "Elapsed: {{time}}",
    "stackingHint": "The SUNSCAN does not report its progress. Stay on this screen.",
    "stackingFailed": "Stacking failed",
    "stackingFailedHint": "Check the connection to the SUNSCAN, then try again.",
    // scan alignment assistant
    "assistant": "Assist",
    "shearAngle": "tilt",
    "quality_excellent": "Ideal window",
    "quality_good": "Good window",
    "quality_fair": "Workable",
    "quality_poor": "Strongly skewed",
    "quality_impossible": "Disk will not fit",
    "assistantSunDown": "Sun below the horizon",
    "assistantNoLocation": "Waiting for a GPS position to compute the scan",
    "assistantLocationDenied": "Location denied: the assistant needs your position",
    "assistantLocationUnavailable": "No GPS fix",
    "assistantOpenSettings": "tap to open settings",
    "assistantRetry": "tap to retry",
    "assistantNoSignal": "Centre the Sun on the slit to start the guidance",
    "assistantShiftBy": "Bring the disk to the mark ({{amount}})",
    "assistantReady": "In position — let the Sun drift off upstream, then record",
    "assistantArmed": "Sun clear of the slit, start the scan now",
    "assistantWontFit": "The disk cannot fit, scan closer to solar noon",
    "assistantWindow": "best {{start}}–{{end}}",
    "assistantScanRemaining": "≈ {{seconds}} s left",
    "assistantScanComplete": "The disk has fully crossed, you can stop",
    "scanPreview": "disk preview",
    "autoStopIn": "Auto stop in {{seconds}} s",
    "autoStopCancel": "tap to cancel",
    // spectral line identification
    "ident": "Ident.",
    "identStarting": "Starting…",
    "identSearching": "Locating the spectrum…",
    "identUnknown": "Spectrum not recognised",
    "identDark": "Not enough light : put the Sun on the slit",
    "identSaturated": "Saturated : lower the exposure",
    "identFlat": "No line in sight : check the focus",
    "identShort": "Spectrum too narrow to identify",
    "identSilent": "No profile received from the SUNSCAN",
    "identUnsupported": "SUNSCAN update required",
    "identLines": "{{n}} lines",
    "identSolar": "Sun",
    "identTelluric": "Earth's atmosphere",
    // home wifi
    "wifiNetwork": "SUNSCAN wifi",
    "wifiModeHotspot": "Hotspot {{ssid}}",
    "wifiModeClient": "Connected to {{ssid}} ({{ip}})",
    "wifiModeConnecting": "Connecting…",
    "wifiModeDisconnected": "Disconnected",
    "wifiConnectHome": "Connect to my wifi",
    "wifiBackToHotspot": "Back to hotspot",
    "wifiBackToHotspotConfirm": "The SUNSCAN will switch back to its hotspot {{hotspot}} and the connection will be lost. Saved networks are kept: at next startup, it will join your wifi again if it is in range.",
    "wifiRejoinHotspot": "Connect your phone to the {{hotspot}} wifi network.",
    "wifiSavedNetworks": "Saved networks",
    "wifiSavedNetworksHint": "Joined automatically at startup when in range.",
    "wifiForget": "Forget",
    "wifiForgetConfirm": "Forget {{ssid}}? The SUNSCAN will no longer join this network.",
    "wifiForgetCurrentConfirm": "Forget {{ssid}}? The SUNSCAN is currently on this network: it will switch back to its hotspot {{hotspot}} and the connection will be lost.",
    "wifiChooseNetwork": "Choose your wifi network",
    "wifiScanning": "The SUNSCAN is looking for networks…",
    "wifiScanCached": "Scan failed, these are the previous results.",
    "wifiRetry": "Retry",
    "wifiNoNetwork": "No network found.",
    "wifiOtherNetwork": "Other network…",
    "wifiUnsupported": "not supported",
    "wifiSaved": "saved",
    "wifiInUse": "current",
    "wifiSsid": "Network name (SSID)",
    "wifiPassword": "Password",
    "wifiPasswordOptional": "Password (empty if none)",
    "wifiConnect": "Connect",
    "wifiClose": "Close",
    "wifiJoining": "The SUNSCAN is joining {{ssid}}…",
    "wifiJoiningHint": "The connection with the SUNSCAN is going to be lost, this is normal.",
    "wifiPutPhoneOn": "Now connect your phone to {{ssid}}.",
    "wifiOpenWifiSettings": "Open wifi settings",
    "wifiConnected": "SUNSCAN connected to {{ssid}}",
    "wifiConnectedHint": "The app now reaches it at {{url}}. Away from this network, the SUNSCAN starts its hotspot again: turn hotspot mode back on in the settings.",
    "wifiFailedHint": "The SUNSCAN is back on its hotspot {{hotspot}}.",
    "wifiLost": "SUNSCAN not found",
    "wifiLostPhone": "Check that your phone is on {{ssid}},",
    "wifiLostHotspot": "or reconnect it to the hotspot {{hotspot}}.",
    "wifiSearchAgain": "Search again",
    "wifiEnterIp": "Enter IP manually",
    "wifiUnreachable": "Could not reach the SUNSCAN.",
    "wifiError_invalid_ssid": "Invalid network name",
    "wifiError_invalid_password": "The password must be 8 to 63 characters long",
    "wifiError_unsupported_security": "This type of network (WEP, enterprise) is not supported",
    "wifiError_busy": "A connection is already in progress, try again in a minute",
    "wifiError_not_supported": "This SUNSCAN cannot join a wifi network",
    "wifiError_wrong_password": "Wrong password",
    "wifiError_network_not_found": "Network not found (out of range, or misspelled name)",
    "wifiError_timeout": "The network did not answer in time",
    "wifiError_no_address": "Connected, but the router gave no address",
    "wifiError_connection_failed": "Connection failed",
}
